[phases.setup]
nixPkgs = ['python311', 'nodejs-18_x', 'postgresql', 'gcc', 'libpq']

[phases.install]
cmds = [
    'python --version',
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'python manage.py collectstatic --noinput --clear'
]

[start]
cmd = 'python manage.py migrate && python manage.py seed_omop_concepts && python manage.py setup_admin && gunicorn ctomop.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120'