# Generated by Django 4.2.16 on 2026-05-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0059_add_breast_cancer_therapy_vocabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breastcancerfirstlinetherapy',
            name='sort_key',
        ),
        migrations.RemoveField(
            model_name='breastcancerlaterlinetherapy',
            name='sort_key',
        ),
        migrations.RemoveField(
            model_name='breastcancersecondlinetherapy',
            name='sort_key',
        ),
        migrations.AlterField(
            model_name='binetstage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='binetstage',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='binetstage',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='breastcancerfirstlinetherapy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='breastcancerfirstlinetherapy',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='breastcancerfirstlinetherapy',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='breastcancerlaterlinetherapy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='breastcancerlaterlinetherapy',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='breastcancerlaterlinetherapy',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='breastcancersecondlinetherapy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='breastcancersecondlinetherapy',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='breastcancersecondlinetherapy',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='cancerstage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cancerstage',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='cancerstage',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='diseaseactivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diseaseactivity',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='diseaseactivity',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='diseaseprogression',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diseaseprogression',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='diseaseprogression',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='distantmetastasisstage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='distantmetastasisstage',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='distantmetastasisstage',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='ecogstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ecogstatus',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='ecogstatus',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='estrogenreceptorstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estrogenreceptorstatus',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='estrogenreceptorstatus',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='flipiscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flipiscore',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='flipiscore',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='follicularlymphomagrade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='follicularlymphomagrade',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='follicularlymphomagrade',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='gelfcriteria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gelfcriteria',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='gelfcriteria',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='her2status',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='her2status',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='her2status',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='histologictype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='histologictype',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='histologictype',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='hrdstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hrdstatus',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='hrdstatus',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='hrstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hrstatus',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='hrstatus',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='infectionstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='infectionstatus',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='infectionstatus',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='karnofskyscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='karnofskyscore',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='karnofskyscore',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='languageskilllevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='languageskilllevel',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='languageskilllevel',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='measurabledisease',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='measurabledisease',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='measurabledisease',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='morphologicvariant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='morphologicvariant',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='morphologicvariant',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='mutationcode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mutationcode',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='mutationcode',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='mutationgene',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mutationgene',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='mutationgene',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='mutationinterpretation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mutationinterpretation',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='mutationinterpretation',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='mutationorigin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mutationorigin',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='mutationorigin',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='nodesstage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nodesstage',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='nodesstage',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='patienttrialenrollment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patienttrialenrollment',
            name='nct_id',
            field=models.CharField(blank=True, help_text='ClinicalTrials.gov NCT number, e.g. NCT04567890', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patienttrialenrollment',
            name='notes',
            field=models.TextField(blank=True, help_text='Free-text notes from coordinating clinician', null=True),
        ),
        migrations.AlterField(
            model_name='patienttrialenrollment',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('registered', 'Registered'), ('entered', 'Entered'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='interested', help_text="Patient's current enrollment status in this trial", max_length=20),
        ),
        migrations.AlterField(
            model_name='patienttrialenrollment',
            name='status_date',
            field=models.DateField(blank=True, help_text='Date the current status was recorded', null=True),
        ),
        migrations.AlterField(
            model_name='patienttrialenrollment',
            name='trial_id',
            field=models.CharField(help_text='EXACT trial identifier — used to fetch trial metadata from EXACT API', max_length=100),
        ),
        migrations.AlterField(
            model_name='peripheralneuropathygrade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='peripheralneuropathygrade',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='peripheralneuropathygrade',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='preexistingconditioncategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='preexistingconditioncategory',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='preexistingconditioncategory',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='progesteronereceptorstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='progesteronereceptorstatus',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='progesteronereceptorstatus',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='proteinexpression',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proteinexpression',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='proteinexpression',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='richtertransformation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='richtertransformation',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='richtertransformation',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='stagingmodality',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stagingmodality',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='stagingmodality',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='stemcelltransplant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stemcelltransplant',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='stemcelltransplant',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='toxicitygrade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='toxicitygrade',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='toxicitygrade',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='tumorburden',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tumorburden',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='tumorburden',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
        migrations.AlterField(
            model_name='tumorstage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tumorstage',
            name='source_name',
            field=models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True),
        ),
        migrations.AlterField(
            model_name='tumorstage',
            name='source_url',
            field=models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True),
        ),
    ]
