# Generated by Django 5.2.6 on 2026-05-12 17:00

from django.db import migrations, models


RENAME_IDX_SQL = """
ALTER INDEX IF EXISTS prov_content_type_object_idx RENAME TO provenance__content_717887_idx;
ALTER INDEX IF EXISTS prov_ct_obj_idx              RENAME TO provenance__content_717887_idx;
"""

RENAME_IDX_REVERSE_SQL = """
ALTER INDEX IF EXISTS provenance__content_717887_idx RENAME TO prov_content_type_object_idx;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0062_add_provenance_record"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientinfo",
            old_name="pd_l1_tumor_cels",
            new_name="pd_l1_tumor_cells",
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=RENAME_IDX_SQL, reverse_sql=RENAME_IDX_REVERSE_SQL),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="provenancerecord",
                    new_name="provenance__content_717887_idx",
                    old_name="prov_ct_obj_idx",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="applicationorganization",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="provenancerecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
