# Generated by Django 5.2.6 on 2026-05-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0063_rename_pd_l1_tumor_cels_to_cells"),
    ]

    operations = [
        migrations.AddField(
            model_name="provenancerecord",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant organization that authorized this write",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="omop_core.organization",
            ),
        ),
    ]
