# Generated by Django 4.2.16 on 2026-05-20 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0066_fix_relationship_is_hierarchical_integer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoincClass',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'loinc_class',
            },
        ),
        migrations.CreateModel(
            name='CareSite',
            fields=[
                ('care_site_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('care_site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('care_site_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('place_of_service_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='omop_core.location')),
                ('place_of_service_concept', models.ForeignKey(blank=True, db_column='place_of_service_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='care_sites', to='omop_core.concept')),
            ],
            options={
                'db_table': 'care_site',
            },
        ),
    ]
