# Generated by Django 4.2.16 on 2026-05-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0068_create_hk_labs_vocabulary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['person', 'measurement_concept', 'measurement_date'], name='ix_meas_person_concept_date'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['person', 'measurement_source_concept', 'measurement_date'], name='ix_meas_person_srcconcept_date'),
        ),
    ]
