# Generated by Django 4.2.16 on 2026-05-21 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0069_add_measurement_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoincCodeClass',
            fields=[
                ('loinc_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('loinc_class', models.ForeignKey(db_column='loinc_class_code', on_delete=django.db.models.deletion.CASCADE, to='omop_core.loincclass')),
            ],
            options={
                'db_table': 'loinc_code_class',
            },
        ),
    ]
