# Generated by Django 4.2.16 on 2026-05-22 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omop_core', '0070_add_loinc_code_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('rule_managed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_groups', to='omop_core.organization')),
            ],
            options={
                'db_table': 'patient_group',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalGroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('navigator', 'Navigator'), ('doctor', 'Doctor')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='omop_core.patientgroup')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional_group_access',
            },
        ),
        migrations.CreateModel(
            name='PersonalRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.BigIntegerField()),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('spouse', 'Spouse'), ('guardian', 'Guardian'), ('caregiver', 'Caregiver'), ('other', 'Other')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='represented_persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_representative',
            },
        ),
        migrations.CreateModel(
            name='PatientGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.BigIntegerField()),
                ('source', models.CharField(choices=[('manual', 'Manual assignment'), ('rule', 'Rule-based auto-assignment')], default='manual', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='omop_core.patientgroup')),
            ],
            options={
                'db_table': 'patient_group_membership',
            },
        ),
        migrations.AddConstraint(
            model_name='professionalgroupaccess',
            constraint=models.UniqueConstraint(fields=('identity', 'group'), name='uq_identity_group'),
        ),
        migrations.AddConstraint(
            model_name='personalrepresentative',
            constraint=models.UniqueConstraint(fields=('representative', 'person_id'), name='uq_representative_person'),
        ),
        migrations.AddConstraint(
            model_name='patientgroupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'person_id'), name='uq_group_person'),
        ),
        migrations.AddConstraint(
            model_name='patientgroup',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uq_patient_group_org_slug'),
        ),
    ]
