# Generated by Django 4.2.16 on 2026-05-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0071_add_authorization_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['vocabulary_id', 'concept_code'], name='ix_concept_vocab_code'),
        ),
    ]
