# Generated by Django 4.2.16 on 2026-05-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0072_add_concept_vocab_code_and_email_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalrepresentative',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='professionalgroupaccess',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
