# Generated by Django 4.2.16 on 2026-05-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0074_add_pk_sequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientgroupmembership',
            name='person_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='personalrepresentative',
            name='person_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
