# Generated by Django 4.2.16 on 2026-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0079_measurement_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='race',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurementownership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
