# Generated by Django 4.2.16 on 2026-05-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0080_add_race_to_patient_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='mrd_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
