# Generated by Django 4.2.16 on 2026-06-03 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0081_add_mrd_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='Firestore document ID from ~/one (for syncing)', max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('disease', models.CharField(blank=True, default='', max_length=100)),
                ('pages', models.JSONField(default=list, help_text='Array of Form pages; each page has {name, title, inputs[]} matching EpicForm schema')),
                ('estimated_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'survey',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(default=dict, help_text="Field-name → answer value map matching the survey's input names")),
                ('values_dates', models.JSONField(default=dict, help_text='Field-name → ISO timestamp of last update for each answer')),
                ('percent_complete', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('consent_signature', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='omop_core.person')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='omop_core.survey')),
            ],
            options={
                'db_table': 'patient_survey_response',
                'ordering': ['-updated_at'],
                'unique_together': {('person', 'survey')},
            },
        ),
    ]
