# Generated by Django 5.2.6 on 2026-06-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0082_add_survey_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientsurveyresponse",
            name="consent_signature",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="survey",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
