# Generated by Django 4.2.16 on 2026-06-06 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0083_survey_name_unique_consent_sig_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsurveyresponse',
            name='percent_complete',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
