# Generated by Django 5.2.6 on 2026-06-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0084_add_percent_complete_validators"),
    ]

    operations = [
        migrations.CreateModel(
            name="SctEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(db_index=True, unique=True)),
                ("title", models.TextField(db_index=True, unique=True)),
                ("llm_hint", models.TextField(blank=True, null=True)),
                (
                    "source_name",
                    models.TextField(
                        blank=True,
                        help_text="Authoritative vocabulary source name",
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.TextField(
                        blank=True,
                        help_text="URL to the vocabulary standard",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "vocabulary_sct_eligibility",
            },
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="sct_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="sct_eligibility",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Multi-select from SctEligibility vocabulary",
                null=True,
            ),
        ),
    ]
