# Generated by Django 5.2.6 on 2026-06-01 14:55
# Modified 2026-06-08: make SctEligibility CreateModel idempotent (production DB
# already had the table from a prior partial deploy; wrap in SeparateDatabaseAndState
# so migrate does not crash with DuplicateTable on a clean re-run).

from django.db import migrations, models


def backfill_sct_eligibility(apps, schema_editor):
    """Set sct_eligibility=[] on any rows where it is NULL (existing rows pre-migration)."""
    PatientInfo = apps.get_model('omop_core', 'PatientInfo')
    PatientInfo.objects.filter(sct_eligibility__isnull=True).update(sct_eligibility=[])


def reverse_noop(apps, schema_editor):
    pass


# SQL that creates vocabulary_sct_eligibility only if it does not already exist.
# Safe to run whether the table is present (production) or absent (fresh DB / CI).
_CREATE_SCT_ELIGIBILITY = """
CREATE TABLE IF NOT EXISTS "vocabulary_sct_eligibility" (
    "id"          bigserial    NOT NULL PRIMARY KEY,
    "code"        text         NOT NULL,
    "title"       text         NOT NULL,
    "llm_hint"    text         NULL,
    "source_name" text         NULL,
    "source_url"  text         NULL
);

-- Add UNIQUE constraints idempotently (PostgreSQL raises duplicate_object if already present)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conrelid = 'vocabulary_sct_eligibility'::regclass
           AND conname   = 'vocabulary_sct_eligibility_code_key'
    ) THEN
        ALTER TABLE "vocabulary_sct_eligibility"
            ADD CONSTRAINT "vocabulary_sct_eligibility_code_key" UNIQUE ("code");
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conrelid = 'vocabulary_sct_eligibility'::regclass
           AND conname   = 'vocabulary_sct_eligibility_title_key'
    ) THEN
        ALTER TABLE "vocabulary_sct_eligibility"
            ADD CONSTRAINT "vocabulary_sct_eligibility_title_key" UNIQUE ("title");
    END IF;
END
$$;

-- Regular indexes (IF NOT EXISTS is safe on repeat)
CREATE INDEX IF NOT EXISTS "vocabulary_sct_eligibility_code_idx"
    ON "vocabulary_sct_eligibility" ("code");
CREATE INDEX IF NOT EXISTS "vocabulary_sct_eligibility_title_idx"
    ON "vocabulary_sct_eligibility" ("title");
"""


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0084_add_percent_complete_validators"),
    ]

    operations = [
        # SeparateDatabaseAndState: Django model state gets the normal CreateModel so
        # the ORM knows about SctEligibility; the database side uses idempotent SQL so
        # the migration succeeds even when the table already exists.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="SctEligibility",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("code", models.TextField(db_index=True, unique=True)),
                        ("title", models.TextField(db_index=True, unique=True)),
                        ("llm_hint", models.TextField(blank=True, null=True)),
                        (
                            "source_name",
                            models.TextField(
                                blank=True,
                                help_text="Authoritative vocabulary source name",
                                null=True,
                            ),
                        ),
                        (
                            "source_url",
                            models.TextField(
                                blank=True,
                                help_text="URL to the vocabulary standard",
                                null=True,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "vocabulary_sct_eligibility",
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=_CREATE_SCT_ELIGIBILITY,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="sct_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="sct_eligibility",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Multi-select from SctEligibility vocabulary",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_sct_eligibility, reverse_noop),
    ]
