# Generated by Django 5.2.6 on 2026-06-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0086_seed_sct_eligibility_update_stem_cell_transplant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinfo",
            name="plasma_cell_leukemia",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
