# Generated by Django 5.2.6 on 2026-06-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0087_fix_plasma_cell_leukemia_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="actor_iss",
            field=models.CharField(
                blank=True, help_text="OIDC issuer URL", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="actor_sub",
            field=models.CharField(
                blank=True,
                help_text="OIDC subject (Firebase UID)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("actor_iss__isnull", False), ("actor_sub__isnull", False)
                ),
                fields=("actor_iss", "actor_sub"),
                name="person_actor_iss_sub_unique",
            ),
        ),
    ]
