# Generated by Django 5.2.6 on 2026-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0089_canonicalize_myeloma_disease"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitoccurrence",
            name="visit_source_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="visitoccurrence",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("visit_source_value__isnull", False),
                    models.Q(("visit_source_value", ""), _negated=True),
                ),
                fields=(
                    "person",
                    "visit_start_date",
                    "care_site_id",
                    "visit_source_value",
                ),
                name="uq_visit_person_date_site_source",
            ),
        ),
    ]
