# Generated by Django 5.2.6 on 2026-06-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("omop_core", "0090_visit_source_value_255_and_unique_constraint"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="provenancerecord",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id", "source_user_id", "source"),
                name="uq_provenance_object_actor_source",
            ),
        ),
    ]
