# Generated by Django 5.2.6 on 2026-06-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0091_provenance_dedup_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientinfo",
            name="first_line_therapy_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="HemOnc concept_id for first-line regimen",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="later_therapy_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of HemOnc concept_ids for later-line regimens (3L+)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientinfo",
            name="second_line_therapy_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="HemOnc concept_id for second-line regimen",
                null=True,
            ),
        ),
    ]
