# Generated by Django 5.2.6 on 2026-06-19 09:03

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0093_backfill_therapy_hemonc_names"),
    ]

    operations = [
        # Enable pg_trgm extension required by the GIN trigram index below.
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name="concept",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["concept_name"],
                name="ix_concept_name_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
