# Generated by Django 5.2.6 on 2026-06-19 09:03

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0093_backfill_therapy_hemonc_names"),
    ]

    operations = [
        # Enable pg_trgm extension required by the GIN trigram index below.
        # Use RunSQL with IF NOT EXISTS so this is idempotent on databases where
        # the extension was already installed by the hosting provider (e.g. Render).
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name="concept",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["concept_name"],
                name="ix_concept_name_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
