# Generated by Django 5.2.6 on 2026-06-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0095_group_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier used in URLs and DAG conf (e.g. 'epic_uw', 'cerner').",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                (
                    "fhir_base",
                    models.URLField(
                        help_text="Base FHIR URL; passed as the `aud` claim during OAuth."
                    ),
                ),
                (
                    "smart_config_url",
                    models.URLField(
                        help_text=".well-known/smart-configuration; resolves authorize + token endpoints."
                    ),
                ),
                ("client_id", models.CharField(max_length=200)),
                (
                    "scopes",
                    models.CharField(
                        help_text="Space-separated OAuth scopes requested at /authorize.",
                        max_length=500,
                    ),
                ),
                (
                    "redirect_uri",
                    models.URLField(
                        help_text="Must match the redirect URI registered with the vendor."
                    ),
                ),
                (
                    "jwks_kid",
                    models.CharField(
                        blank=True,
                        help_text="`kid` of the signing key in our JWKS. Empty disables JWT client auth.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "supports_bulk_export",
                    models.BooleanField(
                        default=False,
                        help_text="True → fhir_extract uses $export; False → paginated fallback.",
                    ),
                ),
                ("base_backoff_seconds", models.IntegerField(default=1)),
                ("max_backoff_seconds", models.IntegerField(default=300)),
                ("max_retry_count", models.IntegerField(default=5)),
                ("respect_retry_after", models.BooleanField(default=True)),
                ("jitter_factor", models.FloatField(default=0.1)),
                (
                    "retryable_status_codes",
                    models.JSONField(
                        default=list,
                        help_text="HTTP statuses treated as transient (e.g. [429, 502, 503, 504]).",
                    ),
                ),
                (
                    "daily_quota_reset_utc_hour",
                    models.IntegerField(
                        blank=True,
                        help_text="UTC hour at which the vendor's daily quota resets, if applicable.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fhir_institution",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="FhirOauthState",
            fields=[
                (
                    "state",
                    models.CharField(
                        help_text="The OAuth `state` query param; verified on callback.",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_verifier", models.CharField(max_length=128)),
                ("nonce", models.CharField(max_length=64)),
                (
                    "return_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="App-internal path to redirect to on successful callback.",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        db_column="person_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fhir_oauth_states",
                        to="omop_core.person",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omop_core.institution",
                    ),
                ),
            ],
            options={
                "db_table": "fhir_oauth_state",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="fhir_oauth__created_88ad7f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FhirConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token_encrypted", models.TextField()),
                ("refresh_token_encrypted", models.TextField()),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="UTC instant at which access_token expires."
                    ),
                ),
                (
                    "scope_granted",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "fhir_patient_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("expiring_soon", "Expiring soon"),
                            ("needs_reauth", "Needs re-authentication"),
                            ("revoked", "Revoked by patient"),
                            ("degraded", "Degraded (repeated failures)"),
                        ],
                        default="connected",
                        max_length=20,
                    ),
                ),
                ("last_successful_sync", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_sync", models.DateTimeField(blank=True, null=True)),
                ("last_token_refresh_at", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning tenant org, derived from the session that initiated the connect.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fhir_connections",
                        to="omop_core.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        db_column="person_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fhir_connections",
                        to="omop_core.person",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connections",
                        to="omop_core.institution",
                    ),
                ),
            ],
            options={
                "db_table": "fhir_connection",
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="fhir_connec_expires_2eda7d_idx"
                    ),
                    models.Index(
                        fields=["status"], name="fhir_connec_status_1a2a89_idx"
                    ),
                    models.Index(
                        fields=["institution", "status"],
                        name="fhir_connec_institu_dec11e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "institution"),
                        name="fhir_connection_person_institution_unique",
                    )
                ],
            },
        ),
    ]
