# Generated by Django 4.2.16 on 2026-06-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0097_org_management'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orgtrust',
            constraint=models.CheckConstraint(check=models.Q(('trusted_org__isnull', True), models.Q(('trusted_org', models.F('granting_org')), _negated=True), _connector='OR'), name='org_trust_no_self_trust'),
        ),
    ]
