# Generated by Django 5.2.6 on 2026-06-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0097_org_management"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="patientinfo",
            index=models.Index(fields=["-updated_at"], name="ix_pi_updated_at"),
        ),
        migrations.AddIndex(
            model_name="patientinfo",
            index=models.Index(
                fields=["organization", "-updated_at"], name="ix_pi_org_updated_at"
            ),
        ),
    ]
