# Generated by Django 5.2.6 on 2026-06-29 13:49
# Amended: use IF NOT EXISTS so the migration is idempotent if the index was
# already created outside of Django's migration history.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0097_org_management"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS ix_pi_updated_at ON patient_info (updated_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS ix_pi_updated_at;",
            state_operations=[
                migrations.AddIndex(
                    model_name="patientinfo",
                    index=models.Index(fields=["-updated_at"], name="ix_pi_updated_at"),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS ix_pi_org_updated_at ON patient_info (organization_id, updated_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS ix_pi_org_updated_at;",
            state_operations=[
                migrations.AddIndex(
                    model_name="patientinfo",
                    index=models.Index(
                        fields=["organization", "-updated_at"], name="ix_pi_org_updated_at"
                    ),
                ),
            ],
        ),
    ]
