# Generated by Django 5.2.6 on 2026-06-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0098_add_patient_info_filter_indexes"),
        ("omop_core", "0098_org_trust_no_self_trust"),
    ]

    operations = []
