# Generated by Django 4.2.16 on 2026-06-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0099_merge_20260629_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='active_minutes_per_day_30d',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Mean daily active/exercise minutes over last 30 days', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='activity_trend_30d',
            field=models.CharField(blank=True, help_text='Activity trend: improving, stable, declining, or insufficient_data', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='hrv_sdnn_avg_30d',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Mean HRV SDNN over last 30 days (ms)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='median_daily_steps_30d',
            field=models.IntegerField(blank=True, help_text='Median daily step count over valid days in last 30 days', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='oxygen_saturation_min_30d',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum valid SpO2 reading over last 30 days (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='respiratory_rate_avg_30d',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Mean respiratory rate over last 30 days (breaths/min)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='resting_heart_rate_avg_30d',
            field=models.IntegerField(blank=True, help_text='Mean resting heart rate over last 30 days', null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='sleep_duration_hours_avg_30d',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Mean nightly sleep duration over last 30 days (hours)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='wearable_coverage_ratio_30d',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valid wearable days / 30 (data quality indicator)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='wearable_last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Latest wearable sample timestamp', null=True),
        ),
    ]
