# Generated by Django 5.2.6 on 2026-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0100_add_wearable_patientinfo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="allows_public_aggregated_data",
            field=models.BooleanField(
                default=False,
                help_text="When true, aggregated de-identified data from this org is available for analysis in PRism Analytics to any signed-up user. Does not grant access to individual patient records in PRomop.",
            ),
        ),
    ]
