# Generated by Django 5.2.6 on 2026-07-06 13:10
# Hand-edited: replaced Create+Delete with RenameModel+AlterModelTable for safe in-place rename.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0103_rename_navigator_to_analyst"),
    ]

    operations = [
        # Unrelated field changes detected in the same makemigrations run
        migrations.AlterField(
            model_name="groupaccess",
            name="role",
            field=models.CharField(
                choices=[
                    ("org_admin", "Org Admin"),
                    ("doctor", "Doctor"),
                    ("analyst", "Analyst"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orginvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("org_admin", "Org Admin"),
                    ("doctor", "Doctor"),
                    ("analyst", "Analyst"),
                ],
                default="doctor",
                max_length=20,
            ),
        ),
        # Rename the model class in Django's migration state
        migrations.RenameModel(
            old_name="PatientInfo",
            new_name="PatientRecord",
        ),
        # Rename the underlying PostgreSQL table from patient_info → patient_record
        migrations.AlterModelTable(
            name="patientrecord",
            table="patient_record",
        ),
        # Update the related_name on the person OneToOneField (DB-transparent)
        migrations.AlterField(
            model_name="patientrecord",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_record",
                to="omop_core.person",
            ),
        ),
        migrations.RunSQL(
            sql="""
            CREATE VIEW patient_info AS
            SELECT * FROM patient_record;

            CREATE OR REPLACE FUNCTION patient_info_readonly()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'patient_info is a read-only compatibility view; write to patient_record instead';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER patient_info_readonly_trigger
            INSTEAD OF INSERT OR UPDATE OR DELETE ON patient_info
            FOR EACH ROW EXECUTE FUNCTION patient_info_readonly();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS patient_info_readonly_trigger ON patient_info;
            DROP FUNCTION IF EXISTS patient_info_readonly();
            DROP VIEW IF EXISTS patient_info;
            """,
        ),
    ]
