# Generated by Django 5.2.6 on 2026-07-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0105_rename_pi_indexes_to_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='best_response',
            field=models.CharField(blank=True, help_text='Best overall response (e.g. Complete Response, Partial Response, Stable Disease, Progressive Disease)', max_length=50, null=True),
        ),
    ]
