# Generated by Django 5.2.6 on 2026-07-10 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0106_patientrecord_best_response"),
        ("omop_genomics", "0003_remove_genomictestresult_genomic_test_concept_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionEra",
            fields=[
                (
                    "condition_era_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("condition_era_start_date", models.DateField()),
                ("condition_era_end_date", models.DateField()),
                ("condition_occurrence_count", models.IntegerField()),
                (
                    "condition_concept",
                    models.ForeignKey(
                        db_column="condition_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="condition_eras",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        db_column="person_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omop_core.person",
                    ),
                ),
            ],
            options={
                "db_table": "condition_era",
            },
        ),
        migrations.CreateModel(
            name="Death",
            fields=[
                (
                    "person",
                    models.OneToOneField(
                        db_column="person_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="omop_core.person",
                    ),
                ),
                ("death_date", models.DateField()),
                ("death_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "cause_source_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "cause_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="cause_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="death_causes",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "cause_source_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="cause_source_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="death_cause_sources",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "death_type_concept",
                    models.ForeignKey(
                        db_column="death_type_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="death_types",
                        to="omop_core.concept",
                    ),
                ),
            ],
            options={
                "db_table": "death",
            },
        ),
        migrations.CreateModel(
            name="DoseEra",
            fields=[
                (
                    "dose_era_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("dose_value", models.DecimalField(decimal_places=5, max_digits=18)),
                ("dose_era_start_date", models.DateField()),
                ("dose_era_end_date", models.DateField()),
                (
                    "drug_concept",
                    models.ForeignKey(
                        db_column="drug_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dose_eras",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        db_column="person_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omop_core.person",
                    ),
                ),
                (
                    "unit_concept",
                    models.ForeignKey(
                        db_column="unit_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dose_era_units",
                        to="omop_core.concept",
                    ),
                ),
            ],
            options={
                "db_table": "dose_era",
            },
        ),
        migrations.CreateModel(
            name="DrugEra",
            fields=[
                (
                    "drug_era_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("drug_era_start_date", models.DateField()),
                ("drug_era_end_date", models.DateField()),
                ("drug_exposure_count", models.IntegerField()),
                (
                    "drug_concept",
                    models.ForeignKey(
                        db_column="drug_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drug_eras",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        db_column="person_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omop_core.person",
                    ),
                ),
            ],
            options={
                "db_table": "drug_era",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("note_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("note_date", models.DateField()),
                ("note_datetime", models.DateTimeField(blank=True, null=True)),
                ("note_title", models.CharField(blank=True, max_length=255, null=True)),
                ("note_text", models.TextField()),
                ("provider_id", models.IntegerField(blank=True, null=True)),
                ("visit_detail_id", models.IntegerField(blank=True, null=True)),
                (
                    "note_source_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "encoding_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="encoding_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note_encodings",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "language_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="language_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note_languages",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "note_class_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="note_class_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note_classes",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "note_type_concept",
                    models.ForeignKey(
                        db_column="note_type_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note_types",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        db_column="person_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omop_core.person",
                    ),
                ),
                (
                    "visit_occurrence",
                    models.ForeignKey(
                        blank=True,
                        db_column="visit_occurrence_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="omop_core.visitoccurrence",
                    ),
                ),
            ],
            options={
                "db_table": "note",
            },
        ),
        migrations.CreateModel(
            name="NoteNlp",
            fields=[
                (
                    "note_nlp_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("snippet", models.CharField(blank=True, max_length=2500, null=True)),
                ("offset", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "lexical_variant",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("nlp_system", models.CharField(blank=True, max_length=255, null=True)),
                ("nlp_date", models.DateTimeField(blank=True, null=True)),
                ("term_exists", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "term_temporal",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "term_modifiers",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "note",
                    models.ForeignKey(
                        db_column="note_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omop_core.note",
                    ),
                ),
                (
                    "note_nlp_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="note_nlp_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note_nlp_concepts",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "note_nlp_source_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="note_nlp_source_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note_nlp_source_concepts",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "section_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="section_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note_nlp_sections",
                        to="omop_core.concept",
                    ),
                ),
            ],
            options={
                "db_table": "note_nlp",
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "provider_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "provider_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("npi", models.CharField(blank=True, max_length=20, null=True)),
                ("dea", models.CharField(blank=True, max_length=20, null=True)),
                ("year_of_birth", models.IntegerField(blank=True, null=True)),
                (
                    "provider_source_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "specialty_source_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "gender_source_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "care_site",
                    models.ForeignKey(
                        blank=True,
                        db_column="care_site_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="omop_core.caresite",
                    ),
                ),
                (
                    "gender_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="gender_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_gender",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "gender_source_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="gender_source_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_gender_source",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "specialty_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="specialty_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="providers",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "specialty_source_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="specialty_source_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_specialty_source",
                        to="omop_core.concept",
                    ),
                ),
            ],
            options={
                "db_table": "provider",
            },
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "specimen_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("specimen_date", models.DateField()),
                ("specimen_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "specimen_source_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "specimen_source_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "unit_source_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "anatomic_site_source_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "disease_status_source_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "anatomic_site_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="anatomic_site_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specimen_anatomic_sites",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "disease_status_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="disease_status_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specimen_disease_status",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        db_column="person_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omop_core.person",
                    ),
                ),
                (
                    "specimen_concept",
                    models.ForeignKey(
                        db_column="specimen_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specimens",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "specimen_type_concept",
                    models.ForeignKey(
                        db_column="specimen_type_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specimen_types",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "unit_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="unit_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specimen_units",
                        to="omop_core.concept",
                    ),
                ),
            ],
            options={
                "db_table": "specimen",
            },
        ),
        migrations.CreateModel(
            name="VisitDetail",
            fields=[
                (
                    "visit_detail_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("visit_detail_start_date", models.DateField()),
                (
                    "visit_detail_start_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("visit_detail_end_date", models.DateField()),
                (
                    "visit_detail_end_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("provider_id", models.IntegerField(blank=True, null=True)),
                ("care_site_id", models.IntegerField(blank=True, null=True)),
                (
                    "visit_detail_source_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "admitted_from_source_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "discharged_to_source_value",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "preceding_visit_detail_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "parent_visit_detail_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "admitted_from_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="admitted_from_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_detail_admitted_from",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "discharged_to_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="discharged_to_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_detail_discharged_to",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        db_column="person_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omop_core.person",
                    ),
                ),
                (
                    "visit_detail_concept",
                    models.ForeignKey(
                        db_column="visit_detail_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_detail_occurrences",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "visit_detail_source_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="visit_detail_source_concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_detail_source_occurrences",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "visit_detail_type_concept",
                    models.ForeignKey(
                        db_column="visit_detail_type_concept_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_detail_type_occurrences",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "visit_occurrence",
                    models.ForeignKey(
                        blank=True,
                        db_column="visit_occurrence_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="omop_core.visitoccurrence",
                    ),
                ),
            ],
            options={
                "db_table": "visit_detail",
            },
        ),
    ]
