# Generated by Django 4.2.16 on 2026-07-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0110_patientrecord_death_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdmSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdm_source_name', models.CharField(max_length=255)),
                ('cdm_source_abbreviation', models.CharField(max_length=25)),
                ('cdm_holder', models.CharField(max_length=255)),
                ('source_description', models.TextField(blank=True, null=True)),
                ('source_documentation_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('cdm_etl_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('source_release_date', models.DateField(blank=True, null=True)),
                ('cdm_release_date', models.DateField(blank=True, null=True)),
                ('cdm_version', models.CharField(blank=True, max_length=10, null=True)),
                ('vocabulary_version', models.CharField(blank=True, max_length=20, null=True)),
                ('cdm_version_concept', models.ForeignKey(blank=True, db_column='cdm_version_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cdm_sources', to='omop_core.concept')),
            ],
            options={
                'db_table': 'cdm_source',
            },
        ),
        migrations.CreateModel(
            name='SourceToConceptMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(max_length=50)),
                ('source_vocabulary_id', models.CharField(max_length=20)),
                ('source_code_description', models.CharField(blank=True, max_length=255, null=True)),
                ('target_vocabulary_id', models.CharField(max_length=20)),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('invalid_reason', models.CharField(blank=True, max_length=1, null=True)),
                ('source_concept', models.ForeignKey(db_column='source_concept_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stcm_as_source', to='omop_core.concept')),
                ('target_concept', models.ForeignKey(db_column='target_concept_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stcm_as_target', to='omop_core.concept')),
            ],
            options={
                'db_table': 'source_to_concept_map',
                'indexes': [models.Index(fields=['source_code'], name='ix_stcm_source_code')],
            },
        ),
        migrations.CreateModel(
            name='ObservationPeriod',
            fields=[
                ('observation_period_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('observation_period_start_date', models.DateField()),
                ('observation_period_end_date', models.DateField()),
                ('period_type_concept', models.ForeignKey(db_column='period_type_concept_id', on_delete=django.db.models.deletion.PROTECT, related_name='observation_periods', to='omop_core.concept')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='omop_core.person')),
            ],
            options={
                'db_table': 'observation_period',
                'indexes': [models.Index(fields=['person'], name='ix_obs_period_person')],
            },
        ),
        migrations.CreateModel(
            name='DrugStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_value', models.FloatField(blank=True, null=True)),
                ('numerator_value', models.FloatField(blank=True, null=True)),
                ('denominator_value', models.FloatField(blank=True, null=True)),
                ('box_size', models.IntegerField(blank=True, null=True)),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('invalid_reason', models.CharField(blank=True, max_length=1, null=True)),
                ('amount_unit_concept', models.ForeignKey(blank=True, db_column='amount_unit_concept_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_strength_amount_units', to='omop_core.concept')),
                ('denominator_unit_concept', models.ForeignKey(blank=True, db_column='denominator_unit_concept_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_strength_denominator_units', to='omop_core.concept')),
                ('drug_concept', models.ForeignKey(db_column='drug_concept_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_strengths', to='omop_core.concept')),
                ('ingredient_concept', models.ForeignKey(db_column='ingredient_concept_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_strengths', to='omop_core.concept')),
                ('numerator_unit_concept', models.ForeignKey(blank=True, db_column='numerator_unit_concept_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_strength_numerator_units', to='omop_core.concept')),
            ],
            options={
                'db_table': 'drug_strength',
                'indexes': [models.Index(fields=['drug_concept'], name='ix_drug_strength_drug')],
            },
        ),
        migrations.CreateModel(
            name='ConceptSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_synonym_name', models.CharField(max_length=1000)),
                ('concept', models.ForeignKey(db_column='concept_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='synonyms', to='omop_core.concept')),
                ('language_concept', models.ForeignKey(db_column='language_concept_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='concept_synonym_languages', to='omop_core.concept')),
            ],
            options={
                'db_table': 'concept_synonym',
                'indexes': [models.Index(fields=['concept'], name='ix_concept_synonym_concept')],
            },
        ),
    ]
