# Generated by Django 4.2.16 on 2026-07-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0112_seed_cdm_source'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conceptsynonym',
            constraint=models.UniqueConstraint(fields=('concept', 'concept_synonym_name', 'language_concept'), name='uq_concept_synonym_natural_key'),
        ),
        migrations.AddConstraint(
            model_name='drugstrength',
            constraint=models.UniqueConstraint(fields=('drug_concept', 'ingredient_concept'), name='uq_drug_strength_drug_ingredient'),
        ),
    ]
