# Generated by Django 4.2.16 on 2026-07-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0113_conceptsynonym_uq_concept_synonym_natural_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTransformationOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(db_index=True, unique=True)),
                ('title', models.TextField(db_index=True, unique=True)),
                ('llm_hint', models.TextField(blank=True, null=True)),
                ('source_name', models.TextField(blank=True, help_text='Authoritative vocabulary source name', null=True)),
                ('source_url', models.TextField(blank=True, help_text='URL to the vocabulary standard', null=True)),
            ],
            options={
                'db_table': 'vocabulary_post_transformation_outcome',
            },
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='dlbcl_transformation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='post_transformation_outcome',
            field=models.TextField(blank=True, help_text='Vocabulary: PostTransformationOutcome', null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='transformed_to_dlbcl',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
