# Generated by Django 4.2.16 on 2026-07-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0115_seed_post_transformation_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='first_line_component_ids',
            field=models.JSONField(blank=True, default=list, help_text='Component drug concept_ids for the first-line regimen', null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='later_component_ids',
            field=models.JSONField(blank=True, default=list, help_text='Component drug concept_ids across all later-line (3L+) regimens', null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='second_line_component_ids',
            field=models.JSONField(blank=True, default=list, help_text='Component drug concept_ids for the second-line regimen', null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='therapy_component_ids',
            field=models.JSONField(blank=True, default=list, help_text='Aggregate union of component drug concept_ids across all therapy lines', null=True),
        ),
    ]
