# Generated by Django 5.2.6 on 2026-07-23 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0116_patientrecord_first_line_component_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="source",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Provenance: NULL = external vocabulary load; 'HealthKey' = locally authored",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="therapy_ids_provenance",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-field provenance for derived therapy concept_id fields",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RegimenMappingGap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        help_text="Ingest channel that saw the name (e.g. 'fhir-upload')",
                        max_length=50,
                    ),
                ),
                (
                    "source_value",
                    models.CharField(
                        help_text="Raw name/code as received", max_length=255
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        help_text="Normalized form used for matching (lowercase, whitespace-collapsed)",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unmatched", "Unmatched"),
                            ("matched", "Matched"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="unmatched",
                        max_length=20,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("occurrence_count", models.IntegerField(default=1)),
                (
                    "matched_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="matched_concept_id",
                        help_text="Validated concept the name was later matched to, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mapping_gaps_matched",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "quarantine_concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="quarantine_concept_id",
                        help_text="HK-* quarantine concept minted for this name, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mapping_gaps_quarantined",
                        to="omop_core.concept",
                    ),
                ),
            ],
            options={
                "db_table": "regimen_mapping_gap",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_system", "normalized_name"),
                        name="uq_regimen_gap_source_name",
                    )
                ],
            },
        ),
    ]
