# Generated by Django 5.2.6 on 2026-07-23 20:18

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0118_seed_hk_vocabularies_remap_fhir_concepts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conceptsynonym',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('concept_synonym_name'), name='gin_trgm_ops'), name='ix_concept_synonym_name_trgm'),
        ),
    ]
