# Generated by Django 5.2.6 on 2026-07-23 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0118_seed_hk_vocabularies_remap_fhir_concepts"),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabRelease",
            fields=[
                (
                    "release_id",
                    models.CharField(
                        help_text="Opaque id, 'rel-<yyyymmdd>-<6hex>'; also the ETag of the manifest",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("staging", "Staging"), ("published", "Published")],
                        db_index=True,
                        default="staging",
                        max_length=20,
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        default="1.0",
                        help_text="Manifest schema version (bump when the manifest shape changes)",
                        max_length=20,
                    ),
                ),
                (
                    "corpus_scope",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Declared corpus boundary: vocabularies + class/domain scopes that this release governs",
                    ),
                ),
                (
                    "vocabulary_versions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{vocabulary_id: vocabulary_version} captured at publish time",
                    ),
                ),
                (
                    "table_checksums",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{table_name: sha256} over the published rows, for cache validation",
                    ),
                ),
                (
                    "row_counts",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{table_name: row count} at publish time",
                    ),
                ),
                ("build_started_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "vocab_release",
                "ordering": ("-published_at", "-build_started_at"),
            },
        ),
        migrations.AddField(
            model_name="conceptrelationship",
            name="source",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Provenance: NULL = external vocabulary load (Athena); 'HealthKey' = locally authored (e.g. relationships for HealthKey-curated concepts). Mirrors Concept.source.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ReleaseTableChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seq",
                    models.IntegerField(help_text="Apply order within the release"),
                ),
                ("table_name", models.CharField(max_length=50)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("insert", "Insert"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("tombstone", "Tombstone"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "row_key",
                    models.CharField(
                        help_text="Natural key of the changed row (e.g. concept_id or composite)",
                        max_length=255,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="New row image; {old, new} for updates; validity window for tombstones",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        db_column="release_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="omop_core.vocabrelease",
                    ),
                ),
            ],
            options={
                "db_table": "release_table_change",
                "ordering": ("release", "seq"),
                "indexes": [
                    models.Index(fields=["table_name"], name="ix_release_change_table")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("release", "seq"), name="uq_release_change_seq"
                    )
                ],
            },
        ),
    ]
