# Generated by Django 5.2.6 on 2026-07-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0119_vocab_release_models_and_conceptrelationship_source"),
        ("omop_core", "0120_merge_0119_branches"),
    ]

    operations = []
