# Generated by Django 5.2.6 on 2026-07-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0120_merge_0119_branches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("FISH", "FISH"),
                    ("GEP", "GEP"),
                    ("NGS", "NGS"),
                    ("CYTOMETRY", "Flow Cytometry"),
                    ("CYTOGENETICS", "Cytogenetics"),
                    ("LAB_RESULTS", "Lab Results"),
                    ("FULL_MEDICAL_RECORDS", "Full Medical Records"),
                    ("MRD", "MRD"),
                    ("BONE_MARROW", "Bone Marrow"),
                    ("CONSENT", "Consent"),
                    ("IMAGING", "Imaging"),
                    ("ADVANCE_DIRECTIVE", "Advance Directive"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
