# Generated by Django 5.2.6 on 2026-07-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0121_merge_20260724_1704"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sourcetoconceptmap",
            constraint=models.UniqueConstraint(
                fields=(
                    "source_code",
                    "source_vocabulary_id",
                    "target_concept",
                    "valid_start_date",
                ),
                name="uq_stcm_natural_key",
            ),
        ),
    ]
