# Generated by Django 5.2.6 on 2026-07-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0121_add_advance_directive_doc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdocument",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="patient_documents/%Y/%m/"
            ),
        ),
        migrations.AddIndex(
            model_name="drugexposure",
            index=models.Index(fields=["route_source_value"], name="ix_de_route_src"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["qualifier_source_value"], name="ix_obs_qual_src"
            ),
        ),
    ]
