# Generated by Django 5.2.6 on 2026-07-26 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0121_merge_20260724_1704"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabrelease",
            name="build_started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
