# Generated by Django 5.2.6 on 2026-07-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0122_add_clinical_list_indexes_and_document_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabularyRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        default="5.4",
                        help_text="OMOP CDM schema version this release targets.",
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.JSONField(
                        default=list,
                        help_text="List of vocabulary_ids included in this release.",
                    ),
                ),
                (
                    "build_timestamp",
                    models.DateTimeField(help_text="When the vocabulary load started."),
                ),
                (
                    "athena_version",
                    models.CharField(
                        blank=True,
                        help_text="Athena download bundle version string, if known.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "vocab_versions",
                    models.JSONField(
                        default=dict,
                        help_text="Mapping of {vocabulary_id: version} at time of load.",
                    ),
                ),
                (
                    "row_counts",
                    models.JSONField(
                        default=dict,
                        help_text="Mapping of {table_name: row_count} loaded in this release.",
                    ),
                ),
                (
                    "checksums",
                    models.JSONField(
                        default=dict,
                        help_text="Per-table fingerprints for drift detection.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="staged",
                        help_text="Lifecycle state: staged → published → retired.",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this release was promoted to published.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Free-form operator notes about this release.",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "vocabulary_release",
                "ordering": ["-published_at"],
            },
        ),
    ]
