# Generated by Django 5.2.6 on 2026-07-26 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0122_add_clinical_list_indexes_and_document_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterchangeAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(help_text='Name of the external partner / counterparty to the agreement.', max_length=255)),
                ('standards_supported', models.JSONField(blank=True, default=list, help_text='Interchange standards covered, e.g. ["FHIR", "HL7v2"].')),
                ('standard_versions', models.JSONField(blank=True, default=list, help_text='Standard versions covered, e.g. ["R4"].')),
                ('effective_date', models.DateField(help_text='Date the agreement takes effect.')),
                ('expiry_date', models.DateField(blank=True, help_text='Date the agreement expires (null = open-ended).', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='active', max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Convenience flag; false disables the agreement regardless of dates.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner_organization', models.ForeignKey(blank=True, help_text='Local Organization this agreement is associated with, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interchange_agreements', to='omop_core.organization')),
            ],
            options={
                'db_table': 'interchange_agreement',
                'ordering': ['partner_name', '-effective_date'],
            },
        ),
    ]
