# Generated by Django 5.2.6 on 2026-07-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0122_add_clinical_list_indexes_and_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='deprecated_date',
            field=models.DateField(blank=True, help_text='Date the vocabulary was marked deprecated.', null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='deprecated_reason',
            field=models.TextField(blank=True, help_text='Optional human-readable reason for deprecation.', null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='is_deprecated',
            field=models.BooleanField(db_default=False, db_index=True, default=False, help_text='True when this entire code system is retired/withdrawn.'),
        ),
        migrations.CreateModel(
            name='VocabularyVersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary_id', models.CharField(db_index=True, max_length=20)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('cdm_release_date', models.DateField(blank=True, null=True)),
                ('action', models.CharField(choices=[('loaded', 'Loaded'), ('replaced', 'Replaced'), ('deprecated', 'Deprecated')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'vocabulary_version_history',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['vocabulary_id', 'created_at'], name='ix_vocab_ver_hist_vocab_time')],
            },
        ),
    ]
