# Generated by Django 5.2.6 on 2026-07-27 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0124_interchangeagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionoccurrence',
            name='erroneous_reason',
            field=models.TextField(blank=True, help_text='Why this record was marked erroneous', null=True),
        ),
        migrations.AddField(
            model_name='conditionoccurrence',
            name='is_erroneous',
            field=models.BooleanField(default=False, help_text='Marked entered-in-error; retained but excluded from normal reads'),
        ),
        migrations.AddField(
            model_name='drugexposure',
            name='erroneous_reason',
            field=models.TextField(blank=True, help_text='Why this record was marked erroneous', null=True),
        ),
        migrations.AddField(
            model_name='drugexposure',
            name='is_erroneous',
            field=models.BooleanField(default=False, help_text='Marked entered-in-error; retained but excluded from normal reads'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='erroneous_reason',
            field=models.TextField(blank=True, help_text='Why this record was marked erroneous', null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='is_erroneous',
            field=models.BooleanField(default=False, help_text='Marked entered-in-error; retained but excluded from normal reads'),
        ),
        migrations.AddField(
            model_name='observation',
            name='erroneous_reason',
            field=models.TextField(blank=True, help_text='Why this record was marked erroneous', null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='is_erroneous',
            field=models.BooleanField(default=False, help_text='Marked entered-in-error; retained but excluded from normal reads'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Date the document takes/took effect (distinct from the upload timestamp)', null=True),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='status',
            field=models.CharField(choices=[('active', 'Active / In effect'), ('superseded', 'Superseded'), ('revoked', 'Revoked')], default='active', help_text='Effective status of the document (advance directives: active/superseded/revoked)', max_length=20),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='suppress_demographics_for_others',
            field=models.BooleanField(default=False, help_text='If set, redact DOB/location/name from responses served to non-owner readers'),
        ),
        migrations.AddField(
            model_name='procedureoccurrence',
            name='erroneous_reason',
            field=models.TextField(blank=True, help_text='Why this record was marked erroneous', null=True),
        ),
        migrations.AddField(
            model_name='procedureoccurrence',
            name='is_erroneous',
            field=models.BooleanField(default=False, help_text='Marked entered-in-error; retained but excluded from normal reads'),
        ),
        migrations.CreateModel(
            name='RecordRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(blank=True, help_text="String form of the acting Identity PK (or 'system')", max_length=255, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('patient_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='omop_core.patientrecord')),
            ],
            options={
                'db_table': 'record_revision',
                'ordering': ['-changed_at', 'field'],
                'indexes': [models.Index(fields=['patient_record', '-changed_at'], name='recrev_pr_ts_idx')],
            },
        ),
    ]
