# Generated by Django 5.2.6 on 2026-07-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0123_vocabularyrelease"),
        ("omop_core", "0125_conditionoccurrence_erroneous_reason_and_more"),
    ]

    operations = []
