# Generated by Django 5.2.6 on 2026-07-27 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0126_merge_vocab_release"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="allows_patient_signup",
            field=models.BooleanField(
                default=False,
                help_text="When true, patients may self-register via the org's public page.",
            ),
        ),
        migrations.AddField(
            model_name="orginvitation",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, accepting the invite links the patient to this person record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="omop_core.person",
            ),
        ),
        migrations.AlterField(
            model_name="groupaccess",
            name="role",
            field=models.CharField(
                choices=[
                    ("org_admin", "Org Admin"),
                    ("doctor", "Doctor"),
                    ("analyst", "Analyst"),
                    ("patient", "Patient"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orginvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("org_admin", "Org Admin"),
                    ("doctor", "Doctor"),
                    ("analyst", "Analyst"),
                    ("patient", "Patient"),
                ],
                default="doctor",
                max_length=20,
            ),
        ),
    ]
