# Generated by Django 5.2.6 on 2026-07-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0129_drop_concept_ix_concept_name_trgm"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="derivation_version",
            field=models.IntegerField(
                default=1,
                help_text="Version of the derivation logic that last computed this row",
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="derived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when this row was last derived from OMOP tables",
                null=True,
            ),
        ),
    ]
