# Generated by Django 5.2.6 on 2026-08-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0130_add_derivation_versioning"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="first_line_component_class_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Therapy-class (drug-class 'type') concept_ids for the first-line regimen",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="later_component_class_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Therapy-class (drug-class 'type') concept_ids across all later-line (3L+) regimens",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="second_line_component_class_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Therapy-class (drug-class 'type') concept_ids for the second-line regimen",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="therapy_component_class_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Aggregate union of therapy-class (drug-class 'type') concept_ids across all therapy lines",
                null=True,
            ),
        ),
    ]
