# Generated by Django 5.2.6 on 2026-08-05 09:03

from django.db import migrations, models


_MYELOMA_TYPES = [
    ('igg-kappa',              'IgG Kappa'),
    ('igg-lambda',             'IgG Lambda'),
    ('iga-kappa',              'IgA Kappa'),
    ('iga-lambda',             'IgA Lambda'),
    ('igd-kappa',              'IgD Kappa'),
    ('igd-lambda',             'IgD Lambda'),
    ('ige-kappa',              'IgE Kappa'),
    ('ige-lambda',             'IgE Lambda'),
    ('igm-kappa',              'IgM Kappa'),
    ('igm-lambda',             'IgM Lambda'),
    ('light-chain-kappa',      'Light Chain Only (Kappa)'),
    ('light-chain-lambda',     'Light Chain Only (Lambda)'),
    ('non-secretory',          'Non-secretory'),
    ('biclonal',               'Biclonal'),
]


def seed_myeloma_types(apps, schema_editor):
    Model = apps.get_model('omop_core', 'MyelomaType')
    for code, title in _MYELOMA_TYPES:
        Model.objects.get_or_create(code=code, defaults={'title': title})


def unseed_myeloma_types(apps, schema_editor):
    Model = apps.get_model('omop_core', 'MyelomaType')
    Model.objects.filter(code__in={code for code, _ in _MYELOMA_TYPES}).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0132_rename_therapy_type_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyelomaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(db_index=True, unique=True)),
                ("title", models.TextField(db_index=True, unique=True)),
                ("llm_hint", models.TextField(blank=True, null=True)),
                (
                    "source_name",
                    models.TextField(
                        blank=True,
                        help_text="Authoritative vocabulary source name",
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.TextField(
                        blank=True,
                        help_text="URL to the vocabulary standard",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "vocabulary_myeloma_type",
            },
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="myeloma_type",
            field=models.CharField(
                blank=True,
                help_text="Myeloma subtype from MyelomaType vocabulary",
                max_length=100,
                null=True,
            ),
        ),
        migrations.RunPython(seed_myeloma_types, unseed_myeloma_types),
    ]
