# Generated by Django 5.2.6 on 2026-08-07 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0133_add_myeloma_type_field_and_vocabulary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WearableUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_type", models.CharField(max_length=10)),
                ("filename", models.CharField(max_length=255)),
                ("samples_created", models.IntegerField(default=0)),
                ("duplicates_skipped", models.IntegerField(default=0)),
                ("sample_summary", models.JSONField(blank=True, default=list)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wearable_uploads",
                        to="omop_core.person",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wearable_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wearable_upload",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
