# Generated by Django 5.2.6 on 2026-08-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0134_add_wearable_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="vo2_max_avg_30d",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Mean VO2 max over last 30 days (mL/kg/min)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
