# Generated by Django 5.2.6 on 2026-08-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0135_add_vo2_max_avg_30d"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="oxygen_saturation_avg_30d",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Mean SpO2 over last 30 days (%)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
