# Generated by Django 5.2.6 on 2026-08-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0136_add_oxygen_saturation_avg_30d"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="active_energy_per_day_30d",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Mean daily active energy burned over last 30 days (kcal)",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="basal_energy_per_day_30d",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Mean daily basal energy burned over last 30 days (kcal)",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="body_mass_avg_30d",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Mean body mass over last 30 days (kg)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="distance_km_per_day_30d",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Mean daily walking/running distance over last 30 days (km)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="flights_climbed_per_day_30d",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Mean daily flights climbed over last 30 days",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="walking_double_support_pct_avg_30d",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Mean double support time percent over last 30 days (%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="walking_hr_avg_30d",
            field=models.IntegerField(
                blank=True,
                help_text="Mean walking heart rate over last 30 days (bpm)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="walking_speed_avg_30d",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Mean walking speed over last 30 days (km/hr)",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="walking_step_length_avg_30d",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Mean walking step length over last 30 days (cm)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
