from django.db import migrations


# The orphan column is exposed by the `patient_info` compatibility view, so it
# cannot be dropped without rebuilding that view. The view's column list is NOT
# the same in every environment: `0104_rename_patientinfo_to_patientrecord`
# created it as `SELECT * FROM patient_record`, and PostgreSQL expands that star
# into a fixed column list at creation time. Databases built purely from the
# migration chain froze 296 columns; staging and production froze 297, because
# `death_date` had been added to the table out-of-band before 0104 ran there.
#
# Hardcoding either list would silently corrupt the other, so the view is
# rebuilt from its own current columns: every column is carried over in its
# original ordinal position, with `status` replaced by a NULL literal of the
# same type. External consumers of `patient_info` see an identical view --
# including `SELECT status`, which only ever returned NULL anyway.

DROP_STATUS_SQL = """
DO $$
DECLARE
    col_list text;
BEGIN
    SELECT string_agg(
               CASE WHEN column_name = 'status'
                    THEN 'NULL::text AS status'
                    ELSE quote_ident(column_name)
               END,
               ', ' ORDER BY ordinal_position)
      INTO col_list
      FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name = 'patient_info';

    IF col_list IS NULL THEN
        -- No compatibility view in this database; just drop the column.
        RAISE NOTICE 'patient_info view not found; dropping column only';
        EXECUTE 'ALTER TABLE patient_record DROP COLUMN IF EXISTS status';
        RETURN;
    END IF;

    -- Dropping the view also drops its INSTEAD OF trigger; the
    -- patient_info_readonly() function it calls is left in place.
    EXECUTE 'DROP VIEW IF EXISTS patient_info';
    EXECUTE 'ALTER TABLE patient_record DROP COLUMN IF EXISTS status';
    EXECUTE format('CREATE VIEW patient_info AS SELECT %s FROM patient_record', col_list);
    EXECUTE '
        CREATE TRIGGER patient_info_readonly_trigger
        INSTEAD OF INSERT OR UPDATE OR DELETE ON patient_info
        FOR EACH ROW EXECUTE FUNCTION patient_info_readonly()';
END
$$;
"""


# Restores the physical column and re-points the view at it. The column was
# empty in every environment when it was dropped, so no data is lost.
RESTORE_STATUS_SQL = """
DO $$
DECLARE
    col_list text;
BEGIN
    EXECUTE 'ALTER TABLE patient_record ADD COLUMN IF NOT EXISTS status TEXT';

    SELECT string_agg(quote_ident(column_name), ', ' ORDER BY ordinal_position)
      INTO col_list
      FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name = 'patient_info';

    IF col_list IS NULL THEN
        RAISE NOTICE 'patient_info view not found; restored column only';
        RETURN;
    END IF;

    EXECUTE 'DROP VIEW IF EXISTS patient_info';
    EXECUTE format('CREATE VIEW patient_info AS SELECT %s FROM patient_record', col_list);
    EXECUTE '
        CREATE TRIGGER patient_info_readonly_trigger
        INSTEAD OF INSERT OR UPDATE OR DELETE ON patient_info
        FOR EACH ROW EXECUTE FUNCTION patient_info_readonly()';
END
$$;
"""


class Migration(migrations.Migration):
    """
    Drop the orphan ``status`` column from ``patient_record``.

    ``0036_add_cll_and_missing_fields`` created the column with raw SQL
    (``ALTER TABLE patient_info ADD COLUMN IF NOT EXISTS status TEXT``).
    ``0040_remove_status_field`` then removed the field from Django's state
    only, on the mistaken assumption that the column had never been created in
    the database. The column therefore outlived the field -- and survived the
    ``patient_info`` -> ``patient_record`` table rename -- leaving every promop
    database reporting ``EXTRA in DB: ['status']`` in the sync check.

    The column was verified empty (zero non-null values) in local, staging, and
    production before this migration was written.

    This is hand-written rather than generated by ``makemigrations``: the field
    is already absent from Django's state, so there is nothing for the
    autodetector to notice. Only a database operation is required.
    """

    dependencies = [
        ("omop_core", "0137_add_apple_watch_health_metrics"),
    ]

    operations = [
        migrations.RunSQL(sql=DROP_STATUS_SQL, reverse_sql=RESTORE_STATUS_SQL),
    ]
