# Generated by Django 5.2.6 on 2026-08-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0140_fix_concept_zero_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='user_edited_fields',
            field=models.JSONField(blank=True, default=list, help_text='Names of OMOP-derived fields a user set directly through the API that the write-through cannot persist to OMOP. refresh_patient_record restores these when re-derivation yields nothing for them, so a hand-entered value is not erased. OMOP still wins whenever it has a value for the field.'),
        ),
    ]
