# Generated by Django 5.2.6 on 2026-08-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0141_patientrecord_user_edited_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='hrv_rmssd_avg_30d',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Mean HRV RMSSD over last 30 days (ms). Garmin HRV Status is RMSSD-based; kept separate from SDNN', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='hrv_sdnn_avg_30d',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Mean HRV SDNN over last 30 days (ms). Apple Health only — SDNN and RMSSD are different statistics and must not be combined', max_digits=6, null=True),
        ),
    ]
