# Generated by Django 5.2.6 on 2026-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('omop_core', '0143_seed_wearable_runtime_concepts'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE UNIQUE INDEX CONCURRENTLY uq_concept_vocabulary_code '
                        'ON concept (vocabulary_id, concept_code)'
                    ),
                    reverse_sql=(
                        'ALTER TABLE concept '
                        'DROP CONSTRAINT uq_concept_vocabulary_code'
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE concept '
                        'ADD CONSTRAINT uq_concept_vocabulary_code '
                        'UNIQUE USING INDEX uq_concept_vocabulary_code'
                    ),
                    reverse_sql=(
                        'CREATE INDEX CONCURRENTLY ix_concept_vocab_code '
                        'ON concept (vocabulary_id, concept_code)'
                    ),
                ),
                migrations.RunSQL(
                    sql='DROP INDEX CONCURRENTLY ix_concept_vocab_code',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='concept',
                    name='ix_concept_vocab_code',
                ),
                migrations.AddConstraint(
                    model_name='concept',
                    constraint=models.UniqueConstraint(
                        fields=('vocabulary_id', 'concept_code'),
                        name='uq_concept_vocabulary_code',
                    ),
                ),
            ],
        ),
    ]
