# Generated by Django 5.2.6 on 2026-08-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0145_organization_clinical_unit_system_and_wbc_units"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="patientrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("latitude__isnull", True), ("longitude__isnull", True)),
                    models.Q(("latitude__isnull", False), ("longitude__isnull", False)),
                    _connector="OR",
                ),
                name="patientrecord_lat_lon_both_or_neither",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("latitude__isnull", True),
                    models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                    _connector="OR",
                ),
                name="patientrecord_latitude_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="patientrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("longitude__isnull", True),
                    models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                    _connector="OR",
                ),
                name="patientrecord_longitude_range",
            ),
        ),
    ]
