# Generated by Django 5.2.6 on 2026-08-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "omop_core",
            "0147_convert_tobacco_to_question_answer",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientrecord",
            name="user_edited_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Legacy compatibility metadata from the retired PatientRecord-to-OMOP write-through. It is not written or consulted by derivation; mapped clinical fields are rebuilt only from OMOP facts.",
            ),
        ),
    ]
