# Generated by Django 5.2.6 on 2026-08-18 04:55

from django.db import migrations, models


def copy_patient_record_profile_to_person(apps, schema_editor):
    Person = apps.get_model('omop_core', 'Person')
    PatientRecord = apps.get_model('omop_core', 'PatientRecord')
    profile_fields = [
        'email',
        'phone_number',
        'facility_name',
        'validated',
        'validated_by',
        'validation_date',
        'suppress_demographics_for_others',
    ]

    for record in PatientRecord.objects.exclude(person_id__isnull=True).iterator():
        updates = {}
        for field in profile_fields:
            value = getattr(record, field)
            if field == 'suppress_demographics_for_others':
                if value is True:
                    updates[field] = value
            elif isinstance(value, bool):
                if value is not None:
                    updates[field] = value
            elif value not in (None, ''):
                updates[field] = value
        if updates:
            Person.objects.filter(person_id=record.person_id).update(**updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0148_alter_patientrecord_user_edited_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='facility_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='suppress_demographics_for_others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='validated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='validated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='validation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(copy_patient_record_profile_to_person, noop_reverse),
    ]
