# Generated by Django 5.2.6 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0149_person_email_person_facility_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='caregiver_availability_status',
            field=models.BooleanField(blank=True, default=None, help_text='Is there an available caregiver for the patient?', null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='consent_capability',
            field=models.BooleanField(blank=True, default=None, help_text='Does the patient have cognitive ability to consent?', null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='contraceptive_use',
            field=models.BooleanField(blank=True, default=None, help_text='Does the patient use contraceptives?', null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='no_geographic_exposure_risk',
            field=models.BooleanField(blank=True, default=None, help_text='Has the patient had geographic exposure to risk?', null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='no_mental_health_disorder_status',
            field=models.BooleanField(blank=True, default=None, help_text='Does the patient have a mental health disorder?', null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='no_substance_use_status',
            field=models.BooleanField(blank=True, default=None, help_text='Does the patient use substances?', null=True),
        ),
    ]
