# Generated by Django 5.2.6 on 2026-08-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0151_mm_lab_fields_decimal_and_flc_ratio"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conditionoccurrence",
            index=models.Index(
                fields=["person", "condition_start_date"],
                name="ix_cond_person_start_date",
            ),
        ),
        migrations.AddIndex(
            model_name="drugexposure",
            index=models.Index(
                fields=["person", "drug_exposure_start_date"],
                name="ix_de_person_start_date",
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["person", "is_erroneous", "measurement_date"],
                name="ix_meas_person_err_date",
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["person", "is_erroneous", "observation_date"],
                name="ix_obs_person_err_date",
            ),
        ),
        migrations.AddIndex(
            model_name="procedureoccurrence",
            index=models.Index(
                fields=["person", "procedure_date"], name="ix_proc_person_date"
            ),
        ),
    ]
