# Generated by Django 5.2.6 on 2026-08-21 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0151_mm_lab_fields_decimal_and_flc_ratio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldConceptMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "vocabulary_id",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "concept_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=30)),
                ("omop_table", models.CharField(blank=True, default="", max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_mappings",
                        to="omop_core.concept",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "field_concept_mapping",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("concept_code", ""), _negated=True),
                        fields=("vocabulary_id", "concept_code"),
                        name="uq_field_concept_mapping_vocab_code",
                    )
                ],
            },
        ),
    ]
