# Generated by Django 5.2.6 on 2026-08-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0152_add_field_concept_mapping"),
        ("omop_core", "0152_add_refresh_perf_indexes"),
    ]

    operations = []
