# Generated by Django 5.2.6 on 2026-08-22 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0152_add_field_concept_mapping"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldSynonym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(db_index=True, max_length=100)),
                ("synonym_text", models.CharField(max_length=200)),
                ("source", models.CharField(default="custom", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "field_synonym",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("field_name", "synonym_text"), name="uq_field_synonym"
                    )
                ],
            },
        ),
    ]
