# Generated by Django 5.2.6 on 2026-08-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0153_field_synonym"),
        ("omop_core", "0153_merge_field_concept_mapping_and_refresh_indexes"),
    ]

    operations = []
