# Generated by Django 5.2.6 on 2026-08-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0154_merge_field_synonym_and_refresh_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldconceptmapping',
            name='multiple',
            field=models.BooleanField(default=False, help_text='Several answers at once, stored comma-joined.'),
        ),
        migrations.AddField(
            model_name='fieldconceptmapping',
            name='source_value',
            field=models.CharField(blank=True, default='', help_text='The *_source_value the fact is keyed by. Derivation matches on this, so a mapping without one cannot make its field writable.', max_length=100),
        ),
        migrations.AddField(
            model_name='fieldconceptmapping',
            name='type_concept_id',
            field=models.IntegerField(blank=True, help_text='OMOP *_type_concept for the written row. Defaults to the lab type concept; facts carried as coded text use the EHR type instead.', null=True),
        ),
        migrations.AddField(
            model_name='fieldconceptmapping',
            name='value_kind',
            field=models.CharField(blank=True, choices=[('number', 'Number'), ('string', 'String'), ('date', 'Date'), ('boolean', 'Boolean')], default='', help_text='Which value column the fact is written to.', max_length=10),
        ),
        migrations.AddField(
            model_name='fieldconceptmapping',
            name='value_vocabulary',
            field=models.CharField(blank=True, default='', help_text='Name of a VocabularyLookup model bounding the answers, e.g. "SctEligibility". Offering a value outside the set promises a write that ingest would drop.', max_length=60),
        ),
    ]
