# Generated by Django 5.2.6 on 2026-08-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0162_seed_field_choices_and_formulas"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fieldchoicecode",
            unique_together={("choice", "vocabulary_id", "code")},
        ),
        migrations.AlterField(
            model_name="fieldchoice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fieldchoicecode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fieldformula",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
