# Generated by Django 5.2.6 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0164_active_status_fields_and_flc_ratios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='kappa_lambda_ratio',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text='Measured serum kappa/lambda ratio',
                max_digits=12,
                null=True,
            ),
        ),
    ]
