# Generated by Django 5.2.6 on 2026-08-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0168_activate_seeded_field_formulas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientrecord",
            name="active_malignancies",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="List of currently active malignancies",
                null=True,
            ),
        ),
    ]
