# Generated by Django 5.2.6 on 2026-08-25 16:52

from django.db import migrations, models


def copy_remission_duration(apps, schema_editor):
    """Copy remission_duration_min values to new remission_duration field."""
    PatientRecord = apps.get_model('omop_core', 'PatientRecord')
    PatientRecord.objects.filter(
        remission_duration_min__isnull=False,
    ).exclude(
        remission_duration_min='',
    ).update(remission_duration=models.F('remission_duration_min'))


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0174_custom_patient_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="remission_duration",
            field=models.TextField(
                blank=True, help_text="Duration of remission", null=True
            ),
        ),
        migrations.RunPython(
            copy_remission_duration,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
