# Generated by Django 5.2.6 on 2026-08-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0175_add_remission_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapyRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(db_index=True, unique=True)),
                ("title", models.TextField(db_index=True, unique=True)),
                ("llm_hint", models.TextField(blank=True, null=True)),
                (
                    "source_name",
                    models.TextField(
                        blank=True,
                        help_text="Authoritative vocabulary source name",
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.TextField(
                        blank=True,
                        help_text="URL to the vocabulary standard",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "therapy_round",
            },
        ),
        migrations.CreateModel(
            name="TherapyClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(db_index=True, unique=True)),
                ("title", models.TextField(db_index=True, unique=True)),
                ("llm_hint", models.TextField(blank=True, null=True)),
                (
                    "source_name",
                    models.TextField(
                        blank=True,
                        help_text="Authoritative vocabulary source name",
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.TextField(
                        blank=True,
                        help_text="URL to the vocabulary standard",
                        null=True,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="concept_id",
                        help_text="HemOnc Component Class concept_id from Athena",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="omop_core.concept",
                    ),
                ),
            ],
            options={
                "db_table": "therapy_class",
            },
        ),
        migrations.CreateModel(
            name="TherapyComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(db_index=True, unique=True)),
                ("title", models.TextField(db_index=True, unique=True)),
                ("llm_hint", models.TextField(blank=True, null=True)),
                (
                    "source_name",
                    models.TextField(
                        blank=True,
                        help_text="Authoritative vocabulary source name",
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.TextField(
                        blank=True,
                        help_text="URL to the vocabulary standard",
                        null=True,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="concept_id",
                        help_text="HemOnc Component or RxNorm Ingredient concept_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="omop_core.concept",
                    ),
                ),
            ],
            options={
                "db_table": "therapy_component",
            },
        ),
        migrations.CreateModel(
            name="TherapyRegimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(db_index=True, unique=True)),
                ("title", models.TextField(db_index=True, unique=True)),
                ("llm_hint", models.TextField(blank=True, null=True)),
                (
                    "source_name",
                    models.TextField(
                        blank=True,
                        help_text="Authoritative vocabulary source name",
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.TextField(
                        blank=True,
                        help_text="URL to the vocabulary standard",
                        null=True,
                    ),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        blank=True,
                        db_column="concept_id",
                        help_text="HemOnc Regimen concept_id from Athena",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="omop_core.concept",
                    ),
                ),
            ],
            options={
                "db_table": "therapy_regimen",
            },
        ),
        migrations.CreateModel(
            name="TherapyComponentClassLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_classes",
                        to="omop_core.therapycomponent",
                    ),
                ),
                (
                    "therapy_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_components",
                        to="omop_core.therapyclass",
                    ),
                ),
            ],
            options={
                "db_table": "therapy_component_class",
                "unique_together": {("component", "therapy_class")},
            },
        ),
        migrations.CreateModel(
            name="TherapyRegimenComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_regimens",
                        to="omop_core.therapycomponent",
                    ),
                ),
                (
                    "regimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regimen_components",
                        to="omop_core.therapyregimen",
                    ),
                ),
            ],
            options={
                "db_table": "therapy_regimen_component",
                "unique_together": {("regimen", "component")},
            },
        ),
        migrations.CreateModel(
            name="DiseaseTherapyRegimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_regimens",
                        to="omop_core.disease",
                    ),
                ),
                (
                    "regimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disease_rounds",
                        to="omop_core.therapyregimen",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disease_regimens",
                        to="omop_core.therapyround",
                    ),
                ),
            ],
            options={
                "db_table": "disease_therapy_regimen",
                "unique_together": {("disease", "round", "regimen")},
            },
        ),
    ]
