# Generated by Django 5.2.6 on 2026-08-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0176_custompatientfield_mode"),
        ("omop_core", "0176_therapy_reference_tables"),
    ]

    operations = []
