# Generated by Django 5.2.6 on 2026-08-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0178_seed_mcl_disease"),
        ("omop_core", "0178_validation_fields_are_person_equivalences"),
    ]

    operations = []
