# Generated by Django 5.2.17 on 2026-08-29 08:17

"""Rejoin the two 0184 leaves.

0184_person_language_skill_constraints (#810) and 0184_source_code_concept_mapping
landed within minutes of each other, both depending on 0183. Django refuses to
run a graph with two leaves at all, so dev could not migrate -- which reddens
every open PR, not just these two.

Neither migration is wrong and neither needs changing; they touch different
tables and are independent. This only tells the graph they both come before
whatever is next.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0184_person_language_skill_constraints'),
        ('omop_core', '0184_source_code_concept_mapping'),
    ]

    operations = [
    ]
