# Generated by Django 5.2.17 on 2026-08-30 08:23

from django.conf import settings
"""Re-orient SourceCodeConceptMapping around source code -> destination concept.

Schema: destination vocabulary, OMOP table, and provenance columns, plus a
blankable source_vocabulary_id so an uncoded source code (a paper lab test
name, free text from a note) can be stored at all.

Data: deletes the HK-* self-mappings.  Those rows named an HK-* minting
vocabulary as their *source code system* and pointed at the very concept
carrying that code, so they mapped nothing -- see #834.  They are logged before
deletion; the reverse is a documented no-op because they carried no curation
decision worth reconstructing.
"""
import logging

from django.db import migrations, models


logger = logging.getLogger(__name__)


def delete_self_mappings(apps, schema_editor):
    """Remove rows whose 'source code system' is an HK-* minting vocabulary.

    Matched on the pairing that makes them meaningless -- an HK-* source
    vocabulary whose source_code is the destination concept's own code -- not
    on the HK-* prefix alone, so a genuinely curated row that happens to sit
    under an HK-* destination is never touched.
    """
    Mapping = apps.get_model('omop_core', 'SourceCodeConceptMapping')
    Concept = apps.get_model('omop_core', 'Concept')

    doomed = []
    for row in Mapping.objects.filter(source_vocabulary_id__startswith='HK-'):
        concept = Concept.objects.filter(concept_id=row.target_concept_id).first()
        if concept is None or concept.concept_code != row.source_code:
            # Not a self-mapping. Leave it; the source_vocabulary_id is still
            # wrong, but a human put something there and it is not ours to drop.
            logger.warning(
                'source_code_concept_mapping %s has HK-* source vocabulary %r but is '
                'not a self-mapping; left in place for manual review.',
                row.id, row.source_vocabulary_id,
            )
            continue
        doomed.append(row)

    for row in doomed:
        logger.warning(
            'Deleting self-mapping source_code_concept_mapping id=%s '
            '(%s:%s -> concept %s, status=%s)',
            row.id, row.source_vocabulary_id, row.source_code,
            row.target_concept_id, row.status,
        )
    if doomed:
        Mapping.objects.filter(id__in=[r.id for r in doomed]).delete()


def restore_self_mappings(apps, schema_editor):
    """Irreversible by design.

    The deleted rows mapped a concept to itself and carried no curation
    decision, so there is nothing to reconstruct. Rolling back leaves them
    absent, which is the correct state either way.
    """


def backfill_destination_vocabulary(apps, schema_editor):
    """Populate destination_vocabulary_id from the concept each row points at."""
    Mapping = apps.get_model('omop_core', 'SourceCodeConceptMapping')
    Concept = apps.get_model('omop_core', 'Concept')

    rows = list(Mapping.objects.all())
    if not rows:
        return
    vocab_by_concept = dict(
        Concept.objects.filter(
            concept_id__in={r.target_concept_id for r in rows},
        ).values_list('concept_id', 'vocabulary_id')
    )
    for row in rows:
        row.destination_vocabulary_id = vocab_by_concept.get(row.target_concept_id, '') or ''
    Mapping.objects.bulk_update(rows, ['destination_vocabulary_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0190_drop_fabricated_language_vocabulary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecodeconceptmapping',
            name='destination_vocabulary_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Vocabulary of the destination concept. An HK-* value means the concept was minted locally; a standard vocabulary (SNOMED, LOINC, ...) means a curator re-pointed it at real Athena content.', max_length=20),
        ),
        migrations.AddField(
            model_name='sourcecodeconceptmapping',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcecodeconceptmapping',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcecodeconceptmapping',
            name='occurrence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sourcecodeconceptmapping',
            name='omop_table',
            field=models.CharField(blank=True, default='', help_text='Clinical table the fact lands in (measurement, condition, ...).', max_length=30),
        ),
        migrations.AddField(
            model_name='sourcecodeconceptmapping',
            name='origin',
            field=models.CharField(choices=[('import', 'Import'), ('curator', 'Curator')], db_index=True, default='curator', max_length=10),
        ),
        migrations.AddField(
            model_name='sourcecodeconceptmapping',
            name='origin_system',
            field=models.CharField(blank=True, default='', help_text="Ingest channel that raised it, e.g. 'fhir-upload', 'hk-labs'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='sourcecodeconceptmapping',
            name='source_vocabulary_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='External code system the code arrived in (ICD10CM, LOINC, SNOMED, NDC, ...). Blank means uncoded — a paper lab test name or free text from a note, which is legitimate and common. Never an HK-* vocabulary: those are minting destinations, not source systems.', max_length=50),
        ),
        migrations.AddIndex(
            model_name='sourcecodeconceptmapping',
            index=models.Index(fields=['destination_vocabulary_id', 'status'], name='ix_sccm_dest_status'),
        ),
        migrations.RunPython(delete_self_mappings, restore_self_mappings),
        migrations.RunPython(backfill_destination_vocabulary, migrations.RunPython.noop),
    ]
