# Generated by Django 5.2.17 on 2026-08-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0192_source_code_mapping_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecodeconceptmapping',
            name='target_concept',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The OMOP concept this source code means. Null while a code has been seen but has no destination yet -- a LOINC code whose concept is not loaded on this deploy, say. That is a real review-queue state, and it also keeps the row visible if a vocabulary reload removes the concept it pointed at (db_constraint=False permits exactly that, and a non-nullable FK would hide the orphan behind an INNER JOIN).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_code_mappings', to='omop_core.concept'),
        ),
    ]
