# Generated by Django 5.2.17 on 2026-08-31 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Record who signed a source code mapping off, and when.

    ``created_by``/``updated_by`` say who last touched the row; they do not say
    who approved it, and any later edit overwrites them. ``reviewer`` and
    ``reviewed_at`` are stamped on the proposed -> approved transition only, so
    the sign-off survives every subsequent save.

    **No backfill, deliberately.** Rows already approved carry no reliable
    signal of who approved them: ``updated_by`` is whoever saved the row last,
    which may be a different person doing a later edit, or null for a row an
    import wrote. Copying it into ``reviewer`` would assert a fact we do not
    know, and it would be indistinguishable from a real sign-off. Existing
    approved rows therefore keep ``reviewer``/``reviewed_at`` null, which reads
    honestly as "approved before we recorded this".
    """

    dependencies = [
        ('omop_core', '0193_source_code_mapping_nullable_destination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecodeconceptmapping',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the mapping was approved. Distinct from updated_at, which moves on every save.', null=True),
        ),
        migrations.AddField(
            model_name='sourcecodeconceptmapping',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='The human who approved this mapping. Stamped on the proposed -> approved transition only, so a later edit by someone else does not reassign the sign-off. Null means never approved (or approved before this field existed).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
