# Generated by Django 5.2.6 on 2026-09-01 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0195_detach_code_named_suggest_placeholders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptrelationship",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conceptrelationship",
            name="origin_system",
            field=models.CharField(
                blank=True,
                help_text="'curator', 'suggest', 'fhir-upload', etc.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conceptrelationship",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="When approved.", null=True
            ),
        ),
        migrations.AddField(
            model_name="conceptrelationship",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="Who approved. The high-stakes decision in a mapping.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conceptrelationship",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="NULL = Athena-loaded, 'HealthKey' = curated by us.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conceptrelationship",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="'proposed', 'approved', 'rejected'. NULL = Athena.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conceptrelationship",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
