# Generated by Django 5.2.6 on 2026-09-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0197_mirror_approved_mappings_to_cr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conceptrelationship",
            name="source",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="NULL = Athena-loaded, 'HealthKey' = curated by us.",
                max_length=50,
                null=True,
            ),
        ),
    ]
