# Generated by Django 5.2.6 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0201_seed_hklabs_sccm'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyrelease',
            name='umls_release',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Raw UMLS archive provenance cached alongside this Athena load.',
            ),
        ),
    ]
