# Generated by Django 5.2.6 on 2026-09-05 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0204_concept_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptEmbedding",
            fields=[
                (
                    "concept",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="embedding",
                        serialize=False,
                        to="omop_core.concept",
                    ),
                ),
                (
                    "embedding",
                    models.BinaryField(
                        help_text="pgvector vector(384) stored via raw SQL; BinaryField is a placeholder for Django."
                    ),
                ),
            ],
            options={
                "db_table": "concept_embedding",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="sourcecodeconceptmapping",
            name="suggest_strategy",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which retrieval tier proposed this mapping: umls, vectors, or lexical. Blank for curator-created rows or rows from before this field existed.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sourcecodeconceptmapping",
            name="umls_cui",
            field=models.CharField(
                blank=True,
                default="",
                help_text="UMLS CUI used to bridge this mapping, when suggest_strategy is umls.",
                max_length=20,
            ),
        ),
    ]
