# Generated by Django 5.2.17 on 2026-09-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0205_source_code_mapping_suggestion_outcome"),
        ("omop_core", "0206_concept_embedding_managed"),
    ]

    operations = []
