# Generated by Django 5.2.17 on 2026-09-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0207_merge_20260905_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcecodeconceptmapping",
            name="umls_source_name",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Canonical UMLS preferred name for this source code, looked up from UmlsSourceCode during suggestion or backfill. Read-only complement to source_code_description: curators edit the description, UMLS name is preserved as-is for reference.",
            ),
        ),
        migrations.AlterField(
            model_name="sourcecodeconceptmapping",
            name="suggestion_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accepted", "Accepted"),
                    ("overridden", "Overridden"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="",
                help_text="Immutable first curator disposition of a machine suggestion.",
                max_length=12,
            ),
        ),
    ]
