# Generated by Django 5.2.17 on 2026-09-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0208_add_umls_source_name_to_sccm"),
        ("omop_core", "0209_backfill_case_insensitive_suggest_provenance"),
    ]

    operations = []
