# Generated by Django 5.2.17 on 2026-09-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0212_suggest_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestEmbeddingSnapshot',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('fingerprint', models.JSONField(default=list)),
                ('candidate_ids', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'suggest_embedding_snapshot',
            },
        ),
    ]
