# Generated by Django 5.2.17 on 2026-09-08 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0213_suggest_embedding_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingDestinationCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_vocabulary_id", models.CharField(max_length=50)),
                ("target_concept_code", models.CharField(max_length=50)),
                ("origins", models.JSONField(default=list)),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_candidates",
                        to="omop_core.sourcecodeconceptmapping",
                    ),
                ),
                (
                    "target_concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="omop_core.concept",
                    ),
                ),
            ],
            options={
                "db_table": "mapping_destination_candidate",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "mapping",
                            "target_vocabulary_id",
                            "target_concept_code",
                        ),
                        name="uq_mapping_destination_candidate",
                    )
                ],
            },
        ),
    ]
