# Generated by Django 5.2.17 on 2026-09-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0217_seed_dropdown_field_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcecodeconceptmapping",
            name="umls_cui",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma-separated UMLS CUIs used to retrieve candidates for this mapping.",
            ),
        ),
    ]
