# Generated by Django 5.2.17 on 2026-09-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0218_expand_mapping_umls_cuis"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestrun",
            name="activity",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="suggestrun",
            name="selection",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
