# Generated by Django 5.2.17 on 2026-09-10 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0219_suggest_run_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="therapy_overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="fieldconceptmapping",
            name="source_value",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The *_source_value the fact is keyed by. Defaults to the concept code when blank, which is correct for standard LOINC/SNOMED mappings. Set an explicit value only when a different key is needed.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="patientrecord",
            name="user_edited_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Fields directly edited by a user that may not yet have OMOP backing. Derivation preserves these values when no OMOP fact exists for the field, and auto-cleans entries once an OMOP fact is projected.",
            ),
        ),
        migrations.CreateModel(
            name="TherapyOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=60)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "diseases",
                    models.ManyToManyField(
                        related_name="therapy_outcomes", to="omop_core.disease"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="SupportiveTherapyCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("intent", models.CharField(blank=True, default="", max_length=50)),
                (
                    "discontinuation_reason",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supportive_courses",
                        to="omop_core.person",
                    ),
                ),
                (
                    "regimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="omop_core.therapyregimen",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("start_date__isnull", True),
                            ("end_date__gte", models.F("start_date")),
                            _connector="OR",
                        ),
                        name="supportive_course_date_order",
                    )
                ],
            },
        ),
    ]
