# Generated by Django 5.2.17 on 2026-09-11 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0221_seed_treatment_editor_catalogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialSearchPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text="Opaque filter payload, camelCase as EXACT's query params spell it (searchTitle, trialType, phase, …). Not validated against a schema here — see the class docstring.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'trial search preferences',
                'db_table': 'trial_search_preferences',
            },
        ),
        migrations.AddField(
            model_name='patienttrialenrollment',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Patient bookmarked this trial. Deliberately a field and not a sixth `status`: the statuses describe participation, and a bookmark is orthogonal to it — a patient can save a trial they will never register for, and register for one they never saved. As a status the two could not be true at once.'),
        ),
        migrations.AddIndex(
            model_name='patienttrialenrollment',
            index=models.Index(fields=['person', 'is_favorite'], name='pte_person_favorite_idx'),
        ),
        migrations.AddField(
            model_name='trialsearchpreferences',
            name='person',
            field=models.OneToOneField(help_text='The patient whose search these preferences belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='trial_search_preferences', to='omop_core.person'),
        ),
    ]
