# Generated by Django 5.2.17 on 2026-09-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0223_backfill_approved_suggestion_outcomes"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldconceptmapping",
            name="provenance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("system_generated", "System Generated"),
                    ("curator", "Curator"),
                ],
                db_default="",
                default="",
                help_text="Who supplied the current mapping recipe; blank for unrecorded legacy origins.",
                max_length=20,
            ),
        ),
    ]
