# Generated by Django 5.2.17 on 2026-09-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0224_field_mapping_provenance"),
        ("omop_core", "0227_seed_genomics_v2_components"),
    ]

    operations = []
