# Generated by Django 5.2.17 on 2026-09-13 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0230_cytogenetic_marker_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldValueConceptMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('answer', 'Coded answer'), ('fact', 'Clinical assertion'), ('structured', 'Structured representation')], default='answer', max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='proposed', max_length=20)),
                ('outcome', models.CharField(choices=[('mapped', 'Mapped'), ('needs_review', 'Needs review'), ('ambiguous', 'Ambiguous'), ('no_equivalent', 'No standard equivalent'), ('not_applicable', 'Not applicable'), ('structured', 'Requires structured representation')], default='needs_review', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('vocabulary_release', models.CharField(blank=True, default='', max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'field_value_concept_mapping',
            },
        ),
        migrations.CreateModel(
            name='FieldValueMappingRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('decision', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'field_value_mapping_revision',
            },
        ),
        migrations.AlterUniqueTogether(
            name='fieldchoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fieldchoice',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fieldchoice',
            name='canonical_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldchoice',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fieldchoice',
            name='context_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fieldchoice',
            name='retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='fieldchoice',
            unique_together={('field_name', 'context_key', 'display')},
        ),
        migrations.AddConstraint(
            model_name='fieldchoice',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('field_name', 'context_key', 'code'), name='uq_field_choice_scoped_code'),
        ),
        migrations.AddField(
            model_name='fieldvalueconceptmapping',
            name='choice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='value_mapping', to='omop_core.fieldchoice'),
        ),
        migrations.AddField(
            model_name='fieldvalueconceptmapping',
            name='question_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='omop_core.concept'),
        ),
        migrations.AddField(
            model_name='fieldvalueconceptmapping',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldvalueconceptmapping',
            name='target_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='omop_core.concept'),
        ),
        migrations.AddField(
            model_name='fieldvaluemappingrevision',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='omop_core.fieldvalueconceptmapping'),
        ),
        migrations.AddConstraint(
            model_name='fieldvalueconceptmapping',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome', 'mapped'), ('status', 'approved'), _negated=True), ('target_concept__isnull', False), _connector='OR'), name='field_value_approved_requires_target'),
        ),
        migrations.AddConstraint(
            model_name='fieldvaluemappingrevision',
            constraint=models.UniqueConstraint(fields=('mapping', 'revision'), name='uq_field_value_revision'),
        ),
    ]
