# Generated by Django 5.2.17 on 2026-09-13 15:42

from importlib import import_module

from django.db import migrations, models


# As in 0151, PostgreSQL cannot change a column type while patient_info
# depends on it. Reuse the frozen rebuild SQL to preserve the view's column
# order, NULL placeholders, owner, grants, and read-only trigger. Do not expose
# the new assessment fields through the legacy view as a side effect.
_compat_view = import_module(
    "omop_core.migrations.0151_mm_lab_fields_decimal_and_flc_ratio"
)


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0231_genomics_variant_name_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="b_symptoms",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="bulky_disease",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="flipi_risk_category",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="gelf_criteria_options",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="ldh_upper_limit_normal",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="number_of_nodal_sites",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql=_compat_view.DROP_VIEW_SQL,
            reverse_sql=_compat_view.CREATE_VIEW_SQL,
        ),
        migrations.AlterField(
            model_name="patientrecord",
            name="tumor_grade",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RunSQL(
            sql=_compat_view.CREATE_VIEW_SQL,
            reverse_sql=_compat_view.DROP_VIEW_SQL,
        ),
    ]
