# Generated by Django 5.2.17 on 2026-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0231_genomics_variant_name_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="b_symptoms",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="bulky_disease",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="flipi_risk_category",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="gelf_criteria_options",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="ldh_upper_limit_normal",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="number_of_nodal_sites",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientrecord",
            name="tumor_grade",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
