# Generated by Django 5.2.17 on 2026-09-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0232_disease_assessment_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientrecord",
            name="absolute_neutrophile_count_units",
            field=models.CharField(
                blank=True,
                choices=[
                    ("10*3/uL", "10^3/μL"),
                    ("10*9/L", "10^9/L"),
                    ("CELLS/UL", "cells/μL"),
                    ("CELLS/L", "cells/L"),
                ],
                default="CELLS/UL",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patientrecord",
            name="platelet_count_units",
            field=models.CharField(
                blank=True,
                choices=[
                    ("10*3/uL", "10^3/μL"),
                    ("10*9/L", "10^9/L"),
                    ("CELLS/UL", "cells/μL"),
                    ("CELLS/L", "cells/L"),
                ],
                default="CELLS/UL",
                max_length=10,
                null=True,
            ),
        ),
    ]
