# Generated by Django 5.2.17 on 2026-09-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0237_merge_concurrent_0236_branches"),
    ]

    operations = [
        migrations.AddField(
            model_name="loinccodeclass",
            name="example_units",
            field=models.CharField(
                blank=True,
                default="",
                help_text="EXAMPLE_UNITS from Loinc.csv; empty when LOINC defines no unit.",
                max_length=128,
            ),
        ),
    ]
