# Generated by Django 5.2.17 on 2026-09-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0238_loinc_code_class_example_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestrun",
            name="ranking_model",
            field=models.CharField(blank=True, default="anthropic", max_length=20),
        ),
    ]
