# Generated by Django 5.2.17 on 2026-09-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0239_add_ranking_model_to_suggest_run"),
        ("omop_core", "0240_seed_field_curation_fixture"),
    ]

    operations = []
