# Generated by Django 5.2.17 on 2026-09-17 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0241_merge_20260917_0953"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcecodeconceptmapping",
            name="locked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the lock was acquired. Expires after MAPPING_LOCK_TIMEOUT_MINUTES.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sourcecodeconceptmapping",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User currently editing this mapping. Cleared on save or timeout.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
