import django.db.models.functions.text
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # #1466: btree on UPPER(concept_code), the expression `concept_code__iexact`
    # compiles to. Without it the code branch of concepts/search is unindexable,
    # and because it is OR-ed with the name match the planner gives up on the
    # trigram index too and filters every row of the vocabulary.
    #
    # Generated by makemigrations as a plain AddIndex, then switched to a
    # concurrent build on the pattern of 0128: `concept` holds millions of rows
    # and a plain CREATE INDEX would block writes to it for the whole build.
    # CREATE INDEX CONCURRENTLY cannot run in a transaction (atomic=False) and a
    # failed build leaves an INVALID index of the same name, so the leading
    # DROP ... IF EXISTS makes a retry clean. It is a no-op on the first run.
    atomic = False

    dependencies = [
        ('omop_core', '0242_add_mapping_lock_fields'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP INDEX CONCURRENTLY IF EXISTS ix_concept_code_upper',
            reverse_sql=migrations.RunSQL.noop,
        ),
        AddIndexConcurrently(
            model_name='concept',
            index=models.Index(
                django.db.models.functions.text.Upper('concept_code'),
                name='ix_concept_code_upper',
            ),
        ),
    ]
