import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models

# Frozen here rather than imported from omop_core.models: a migration must keep
# meaning what it meant when it was written.
DOMAINS = ('Condition', 'Drug', 'Measurement', 'Observation', 'Procedure')


def _index(domain):
    return django.contrib.postgres.indexes.GinIndex(
        django.contrib.postgres.indexes.OpClass(
            django.db.models.functions.text.Upper('concept_name'), name='gin_trgm_ops',
        ),
        condition=models.Q(
            ('domain_id', domain), ('invalid_reason__isnull', True), ('standard_concept', 'S'),
        ),
        name=f'ix_concept_trgm_{domain.lower()}',
    )


class Migration(migrations.Migration):
    # #1467: partial trigram indexes over standard, active concepts, one per
    # destination domain, so Suggest's lexical retrieval narrows to rows that
    # can be an answer before Postgres computes a similarity for each.
    #
    # Generated by makemigrations as five plain AddIndex operations, then
    # switched to concurrent builds on the pattern of 0128 and 0243: `concept`
    # holds millions of rows and a plain CREATE INDEX blocks writes for the whole
    # build. CONCURRENTLY cannot run in a transaction (atomic=False), and a
    # failed build leaves an INVALID index of the same name, so each add is
    # preceded by DROP ... IF EXISTS. If the migration stops part-way it is not
    # recorded, and the retry drops and rebuilds all five -- wasteful but correct.
    atomic = False

    dependencies = [
        ('omop_core', '0243_concept_ix_concept_code_upper'),
    ]

    operations = [
        operation
        for domain in DOMAINS
        for operation in (
            migrations.RunSQL(
                sql=f'DROP INDEX CONCURRENTLY IF EXISTS ix_concept_trgm_{domain.lower()}',
                reverse_sql=migrations.RunSQL.noop,
            ),
            AddIndexConcurrently(model_name='concept', index=_index(domain)),
        )
    ]
