import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

# Frozen here rather than imported: a migration must keep meaning what it meant
# when it was written. services.suggest_synonym_terms.refresh is the living copy.
DOMAINS = ('Condition', 'Drug', 'Measurement', 'Observation', 'Procedure')

BACKFILL = """
    INSERT INTO suggest_synonym_term (concept_id, domain_id, term)
    SELECT DISTINCT s.concept_id, c.domain_id, UPPER(s.concept_synonym_name)
    FROM concept_synonym s
    JOIN concept c ON c.concept_id = s.concept_id
    WHERE c.standard_concept = 'S' AND c.invalid_reason IS NULL
      AND c.domain_id = ANY(%s)
"""


def backfill(apps, schema_editor):
    # No ON CONFLICT: the table is empty, SELECT DISTINCT already yields one row
    # per (concept, term), and the unique index does not exist yet -- Django
    # defers an expression index to the end of the migration.
    # An instance with a vocabulary already loaded would otherwise keep using the
    # slow concept_synonym path until its next vocabulary load. A fresh database
    # has no synonyms yet, so this inserts nothing and the loader fills it later.
    schema_editor.execute(BACKFILL, [list(DOMAINS)])


def _index(domain):
    return django.contrib.postgres.indexes.GinIndex(
        django.contrib.postgres.indexes.OpClass(models.F('term'), name='gin_trgm_ops'),
        condition=models.Q(('domain_id', domain)),
        name=f'ix_suggest_syn_{domain.lower()}',
    )


class Migration(migrations.Migration):
    # #1467. Generated by makemigrations as one CreateModel carrying its five
    # trigram indexes, then reordered: table, backfill, *then* indexes. Building
    # a GIN index over rows already in place is far cheaper than maintaining five
    # of them through a multi-million-row insert. Plain (not concurrent) index
    # builds are right here -- the table is new in this same transaction, so
    # there is nobody to block.

    dependencies = [
        ('omop_core', '0244_concept_suggest_domain_trgm_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestSynonymTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=1000)),
                ('concept', models.ForeignKey(db_column='concept_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='omop_core.concept')),
            ],
            options={
                'db_table': 'suggest_synonym_term',
                'constraints': [models.UniqueConstraint(models.F('concept'), django.db.models.functions.text.MD5('term'), name='uq_suggest_synonym_term')],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
        *[
            migrations.AddIndex(model_name='suggestsynonymterm', index=_index(domain))
            for domain in DOMAINS
        ],
    ]
