# Generated by Django 5.2.17 on 2026-09-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0246_suggest_synonym_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaccess',
            name='pending_email_verification',
            field=models.BooleanField(default=False, help_text='Self-signup grant waiting for verified domain access.'),
        ),
    ]
