# Generated by Django 5.2.17 on 2026-09-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0246_suggest_synonym_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingSuggestionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_vocabulary_id', models.CharField(blank=True, max_length=50)),
                ('source_code', models.CharField(max_length=100)),
                ('suggested_target_concept_id', models.BigIntegerField(null=True)),
                ('suggestion_model_version', models.CharField(max_length=20)),
                ('suggestion_outcome', models.CharField(choices=[('accepted', 'Accepted'), ('overridden', 'Overridden'), ('rejected', 'Rejected')], max_length=12)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('mapping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_reviews', to='omop_core.sourcecodeconceptmapping')),
            ],
            options={
                'db_table': 'mapping_suggestion_review',
            },
        ),
    ]
