# Generated by Django 5.2.17 on 2026-09-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0247_groupaccess_pending_email_verification'),
        ('omop_core', '0247_mapping_suggestion_review'),
    ]

    operations = [
    ]
