# Generated by Django 5.2.17 on 2026-09-20 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0248_merge_review_and_email_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loinccodeclass',
            name='property',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='loinccodeclass',
            name='scale_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='CanonicalUnitPreference',
            fields=[
                ('concept', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='omop_core.concept')),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('property', models.CharField(max_length=40)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CanonicalUnitChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_unit', models.CharField(blank=True, max_length=40)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('revision', models.PositiveIntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='omop_core.canonicalunitpreference')),
            ],
        ),
    ]
