# Generated by Django 5.2.17 on 2026-09-20 12:17

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0249_canonical_loinc_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceVocabulary',
            fields=[
                ('vocabulary_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('release_version', models.CharField(max_length=50)),
                ('source_url', models.URLField(max_length=1000)),
                ('archive_sha256', models.CharField(max_length=64)),
                ('term_count', models.PositiveIntegerField(default=0)),
                ('loaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'source_vocabulary',
            },
        ),
        migrations.CreateModel(
            name='SourceVocabularyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.TextField()),
                ('definition', models.TextField(blank=True)),
                ('synonyms', models.JSONField(default=list)),
                ('parents', models.JSONField(default=list)),
                ('semantic_types', models.JSONField(default=list)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('retired', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('search_text', models.TextField()),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omop_core.sourcevocabulary')),
            ],
            options={
                'db_table': 'source_vocabulary_term',
                'indexes': [django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('search_text'), name='gin_trgm_ops'), name='ix_source_vocab_search_trgm')],
                'constraints': [models.UniqueConstraint(fields=('vocabulary', 'code'), name='uq_source_vocab_term_code')],
            },
        ),
    ]
