# Generated by Django 5.2.17 on 2026-09-21 06:43

from django.db import migrations
from django.utils import timezone


def seed_feature_recipes(apps, schema_editor):
    using = schema_editor.connection.alias
    Concept = apps.get_model('omop_core', 'Concept')
    Mapping = apps.get_model('omop_core', 'FieldConceptMapping')
    zero = Concept.objects.using(using).filter(pk=0).first()
    for key in ('genomic_feature', 'feature_type', 'finding_category'):
        Mapping.objects.using(using).get_or_create(
            field_name='genetic_mutations.' + key,
            defaults={
                'concept': zero, 'source_value': 'genomics:' + key,
                'vocabulary_id': '', 'concept_code': '', 'omop_table': 'observation',
                'value_kind': 'string', 'unit': '', 'type_concept_id': 32817,
                'multiple': False, 'status': 'approved', 'reviewed_at': timezone.now(),
                'notes': 'Genomic finding terminology. Source-only component; '
                         'no gene or sequence-variant concept is inferred for chromosome findings.',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0251_load_publisher_source_catalogs'),
    ]

    operations = [
        # Additive recipes only; preserve curator changes and all patient facts.
        migrations.RunPython(seed_feature_recipes, migrations.RunPython.noop),
    ]
