# Generated by Django 5.2.17 on 2026-09-22 13:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0253_reconcile_athena_icd10_mappings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patientrecord',
            index=models.Index(django.db.models.functions.text.Upper('email'), name='ix_pr_email_upper'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(django.db.models.functions.text.Upper('email'), name='ix_person_email_upper'),
        ),
    ]
