# Generated by Django 5.2.17 on 2026-09-23 21:59

import django.db.models.functions.comparison
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0256_reconcile_icd10_mapped_against_stcm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecodeconceptmapping',
            name='source_label_norm',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(django.db.models.lookups.GreaterThanOrEqual(django.db.models.functions.text.Length(django.db.models.functions.comparison.Coalesce('source_code_description', models.Value(''))), models.Value(255)), then=models.Value(None, output_field=models.CharField())), default=django.db.models.functions.comparison.NullIf(models.Func(django.db.models.functions.text.Lower(django.db.models.functions.comparison.Coalesce('source_code_description', models.Value(''))), models.Value('[^a-z0-9%#]+'), models.Value(''), models.Value('g'), function='regexp_replace', output_field=models.CharField()), models.Value('')), output_field=models.CharField()), help_text='Normalised source_code_description, the key a review group is built from: one curated decision per label rather than per vendor code. Generated by the database so it cannot drift from omop_core.services.source_labels.normalise. NULL means the label normalises to nothing (absent, blank or punctuation only) and the row belongs to no group, as does one stored at the column limit and so possibly truncated. Grouping queries must exclude NULL, since SQL would otherwise gather every such row into one. Widening source_code_description means dropping this column, altering that one and re-adding this one in a single migration: Postgres refuses to alter the type of a column a stored generated column reads.', output_field=models.CharField(max_length=255, null=True)),
        ),
        migrations.AddIndex(
            model_name='sourcecodeconceptmapping',
            index=models.Index(fields=['source_vocabulary_id', 'source_label_norm'], name='ix_sccm_label_group'),
        ),
    ]
