# Generated by Django 5.2.17 on 2026-09-23 23:00

from django.db import migrations


def normalize_snomed_oid_mappings(apps, schema_editor):
    from omop_core.data_migrations.snomed_oid_v1 import reconcile, summarize

    print('SNOMED OID reconciliation:', summarize(reconcile(apps, schema_editor.connection)))


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0257_sourcecodeconceptmapping_source_label_norm'),
    ]

    operations = [
        # Irreversible: merged IDs cannot be safely restored after later edits.
        # Duplicate snapshots remain in survivor notes; restore from backup or
        # reconcile manually if rollback is necessary. Clinical rows are untouched.
        migrations.RunPython(normalize_snomed_oid_mappings),
    ]
