# Generated by Django 5.2.17 on 2026-09-24 08:05

from django.db import migrations


def prefer_standard_snomed_identities(apps, schema_editor):
    from omop_core.data_migrations.snomed_crossmap_v1 import reconcile, summarize

    print('Standard SNOMED crossmap reconciliation:', summarize(reconcile(apps, schema_editor.connection)))


class Migration(migrations.Migration):
    atomic = False  # Each batch rechecks eligibility and commits atomically.

    dependencies = [
        ('omop_core', '0259_normalize_snomed_oid_mappings'),
    ]

    operations = [
        # Original definitions are snapshotted in notes. Restoring them after
        # subsequent curation requires manual reconciliation or a backup.
        migrations.RunPython(prefer_standard_snomed_identities),
    ]
