# Generated by Django 5.2.17 on 2026-09-24 09:11

from django.db import migrations


def reconcile_snomed_local_relationships(apps, schema_editor):
    from omop_core.data_migrations.snomed_relationships_v1 import reconcile, summarize
    print('Local SNOMED relationship reconciliation:', summarize(reconcile(apps, schema_editor.connection)))


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('omop_core', '0261_prefer_standard_snomed_identities'),
    ]

    operations = [
        # Prior mappings and candidates remain in notes. Do not overwrite later
        # curation on rollback; recovery requires manual reconciliation/backup.
        migrations.RunPython(reconcile_snomed_local_relationships),
    ]
