# Generated by Django 5.2.17 on 2026-09-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0262_reconcile_snomed_local_relationships"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialsearchpreferences",
            name="weights_wizard_offered",
            field=models.BooleanField(
                default=False,
                help_text="Whether this patient has been offered the weights wizard.",
            ),
        ),
    ]
