# Generated by Django 5.2.17 on 2026-09-25 14:45

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('omop_core', '0263_trial_search_preferences_weights_wizard_offered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecodeconceptmapping',
            name='pending_repoint_concept_ids',
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AddField(
            model_name='suggestrun',
            name='direction',
            field=models.CharField(choices=[('forward', 'Forward'), ('reverse', 'Reverse')], db_default='forward', default='forward', max_length=10),
        ),
        AddIndexConcurrently(
            model_name='sourcecodeconceptmapping',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('source_code_description'), name='gin_trgm_ops'), name='ix_sccm_desc_upper_trgm'),
        ),
    ]
