# Generated by Django 5.2.17 on 2026-09-28 21:43

from collections import defaultdict

from django.db import migrations, models


def backfill_language_skill_concept_ids(apps, schema_editor):
    """Fill the new column for records that already have language rows.

    AddField gives every record [], and the derivation only runs on a refresh,
    so without this a person's recorded languages stay invisible to consumers
    until something unrelated refreshes their record. Same rule as
    ``_language_skill_concept_pairs``: an unset skill_concept is resolved by its
    HK-Language code, and a row the mint cannot resolve is skipped.
    """
    PersonLanguageSkill = apps.get_model('omop_core', 'PersonLanguageSkill')
    PatientRecord = apps.get_model('omop_core', 'PatientRecord')
    Concept = apps.get_model('omop_core', 'Concept')

    mint = dict(
        Concept.objects.filter(vocabulary_id='HK-Language', concept_code__startswith='hkl:')
        .values_list('concept_code', 'concept_id')
    )
    pairs = defaultdict(set)
    rows = PersonLanguageSkill.objects.values_list(
        'person_id', 'language_concept_id', 'skill_concept_id', 'skill_level')
    for person_id, language_id, skill_id, skill_level in rows.iterator():
        if skill_id is None:
            skill_id = mint.get(f'hkl:{skill_level}')
        if skill_id is None:
            continue
        pairs[person_id].add(f'{language_id}:{skill_id}')
    for person_id, person_pairs in pairs.items():
        PatientRecord.objects.filter(person_id=person_id).update(
            language_skill_concept_ids=sorted(person_pairs))


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0265_reconcile_lab_alias_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='language_skill_concept_ids',
            field=models.JSONField(blank=True, default=list, help_text="Derived: sorted '<language_concept_id>:<skill_concept_id>' pairs from PersonLanguageSkill. [] = nothing recorded."),
        ),
        migrations.RunPython(backfill_language_skill_concept_ids, migrations.RunPython.noop),
    ]
