# Generated by Django 5.2.17 on 2026-09-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0265_reconcile_lab_alias_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='language_skill_concept_ids',
            field=models.JSONField(blank=True, default=list, help_text="Derived: sorted '<language_concept_id>:<skill_concept_id>' pairs from PersonLanguageSkill. [] = nothing recorded."),
        ),
    ]
