# Generated by Django 5.2.17 on 2026-09-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0265_reconcile_lab_alias_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoincRelease',
            fields=[
                ('release_version', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('release_url', models.URLField(max_length=500)),
                ('archive_md5', models.CharField(blank=True, default='', max_length=32)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('loinc_count', models.PositiveIntegerField(blank=True, null=True)),
                ('loaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loinc_release',
            },
        ),
    ]
