# Generated by Django 5.2.17 on 2026-09-30 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0270_code_mapping_upload"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sourcecodeconceptmapping",
            name="uq_sccm_source_vocabulary_code",
        ),
        migrations.RemoveIndex(
            model_name="sourcecodeconceptmapping",
            name="ix_sccm_source_code",
        ),
        migrations.AddField(
            model_name="sourcecodeconceptmapping",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Hospital that supplied a local source code. Null means the mapping is global; Epic and Cerner mappings use this field to separate shared vendor namespaces across institutions.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_code_mappings",
                to="omop_core.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="sourcecodeconceptmapping",
            index=models.Index(
                fields=["organization", "source_vocabulary_id", "source_code"],
                name="ix_sccm_org_source_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecodeconceptmapping",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_vocabulary_id", "source_code"),
                name="uq_sccm_org_source_vocabulary_code",
                nulls_distinct=False,
            ),
        ),
    ]
