# Generated by Django 5.2.17 on 2026-10-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0274_source_code_unit_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcecodeconceptmapping",
            name="source_group_occurrence_count",
            field=models.BigIntegerField(
                blank=True,
                help_text="Deduplicated source-record count for this label group when an extract supplies one. Grouped review uses this instead of summing sibling codings that can coexist on the same record.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sourcecodeconceptmapping",
            name="source_metadata",
            field=models.JSONField(
                blank=True,
                db_default={},
                default=dict,
                help_text="Read-only source evidence retained from an import, such as patient counts, category mix, value types and reference-range coverage. It informs curation and is not clinical reference data.",
            ),
        ),
    ]
