# Generated by Django 5.2.17 on 2026-10-03 10:56

from django.db import migrations, models


SOURCE_URL = "https://drive.google.com/drive/u/1/folders/11B-gJzFeEtl0xGxYNRnk6S57_ulkoTYP"
ARTIFACT_FILENAME = "healthtree_hospital_codes_20261002_v1.zip"
ARTIFACT_IDENTITY = "healthtree-hospital-seed-20261002-v1"
ARTIFACT_SHA256 = "4450e37d2c28dfa7c14db9e4c35821d6551a9a83b774760dd7fa02f14c8fba48"
EXPECTED_ROWS = 691_800


def queue_hospital_code_import(apps, schema_editor):
    HospitalCodeImport = apps.get_model("omop_core", "HospitalCodeImport")
    HospitalCodeImport.objects.update_or_create(
        artifact_identity=ARTIFACT_IDENTITY,
        defaults={
            "source_url": SOURCE_URL,
            "artifact_filename": ARTIFACT_FILENAME,
            "artifact_sha256": ARTIFACT_SHA256,
            "expected_rows": EXPECTED_ROWS,
            "outcome": "queued",
        },
    )


def unqueue_hospital_code_import(apps, schema_editor):
    HospitalCodeImport = apps.get_model("omop_core", "HospitalCodeImport")
    HospitalCodeImport.objects.filter(
        artifact_identity=ARTIFACT_IDENTITY,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "omop_core",
            "0275_sourcecodeconceptmapping_source_group_occurrence_count_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalCodeImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.TextField()),
                ("artifact_filename", models.CharField(max_length=255)),
                ("artifact_identity", models.CharField(max_length=255, unique=True)),
                ("artifact_sha256", models.CharField(max_length=64, unique=True)),
                ("expected_rows", models.PositiveIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "hospital_code_import",
                "ordering": ["-created_at"],
            },
        ),
        # The migration records durable intent only. A newly started Celery
        # worker discovers this row and performs the network and bulk work
        # after deployment, outside the migration transaction.
        migrations.RunPython(
            queue_hospital_code_import,
            unqueue_hospital_code_import,
        ),
    ]
