# Generated by Django 5.2.17 on 2026-10-04 08:21

import re

from django.db import migrations, models


# Frozen copies of the note formats omop_core.mapping.suggestions wrote before
# confidence had a column (#1709). Percentages are checked first: a dual-ranker
# or Jev note also contains a "high confidence" label, and its number is the
# one the ranker compared.
_PERCENT_PATTERNS = (
    re.compile(r'Jev wins \((\d{1,3})%'),
    re.compile(r'\(Anthropic (\d{1,3})% vs Jev'),
    re.compile(r'\(Jev (\d{1,3})%\)'),
)
_LABEL = re.compile(r'\b(high|medium|low) confidence\b')
_LABEL_CONFIDENCE = {'high': 0.85, 'medium': 0.55, 'low': 0.25}


def note_confidence(note):
    for pattern in _PERCENT_PATTERNS:
        match = pattern.search(note)
        if match:
            return min(int(match.group(1)), 100) / 100
    match = _LABEL.search(note)
    return _LABEL_CONFIDENCE[match.group(1)] if match else None


def backfill(apps, schema_editor):
    """Recover confidence for proposals a Suggest run made and nobody moved."""
    Mapping = apps.get_model('omop_core', 'SourceCodeConceptMapping')
    rows = (Mapping.objects.filter(status='proposed', origin_system__istartswith='suggest',
                                   target_concept__isnull=False, suggestion_confidence__isnull=True)
            .exclude(notes='').only('pk', 'notes'))
    batch = []
    for row in rows.iterator(chunk_size=2000):
        confidence = note_confidence(row.notes)
        if confidence is not None:
            row.suggestion_confidence = confidence
            batch.append(row)
        if len(batch) >= 2000:
            Mapping.objects.bulk_update(batch, ['suggestion_confidence'])
            batch = []
    if batch:
        Mapping.objects.bulk_update(batch, ['suggestion_confidence'])


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0277_requeue_interrupted_hospital_code_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecodeconceptmapping',
            name='suggestion_confidence',
            field=models.FloatField(blank=True, help_text='Ranker confidence (0-1) in the suggested destination; null when no ranker chose it.', null=True),
        ),
        # Reversing drops the column, which takes the backfill with it.
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
