# Generated by Django 5.2.17 on 2026-10-04 14:05

from django.db import migrations, models


def stamp_approvers(apps, schema_editor):
    """An approved mapping with a recorded reviewer names that reviewer (#1719).

    Before this, approval left provenance alone, so an approved suggestion still
    read system_generated. Only those rows, and blank ones, are stamped. A
    ``curator`` row records a hand edit after approval, which left the reviewer
    unchanged, so the reviewer may not be its author; naming them would invent
    an attribution. Rows with no reviewer (seeded approvals) and proposed rows
    keep what they have: which engine proposed them was never recorded.
    Frozen copy of field_mapping_provenance.user_provenance.
    """
    Mapping = apps.get_model('omop_core', 'FieldConceptMapping')
    rows = list(Mapping.objects.filter(status='approved', reviewer__isnull=False,
                                       provenance__in=('system_generated', ''))
                .select_related('reviewer'))
    for row in rows:
        reviewer = row.reviewer
        row.provenance = (reviewer.email or reviewer.name or str(reviewer.pk))[:100]
    Mapping.objects.bulk_update(rows, ['provenance'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0278_sccm_suggestion_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldconceptmapping',
            name='provenance',
            field=models.CharField(blank=True, db_default='', default='', help_text='Who supplied the mapping in force: the suggest engine and version that proposed it, "curator", or the approving user. Blank for unrecorded legacy origins.', max_length=100),
        ),
        # Irreversible in content: the overwritten value was the uninformative
        # system_generated/curator label, which the reviewer column supersedes.
        migrations.RunPython(stamp_approvers, migrations.RunPython.noop),
    ]
