# Generated by Django 5.2.17 on 2026-10-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0280_corrected_hospital_code_units"),
        ("omop_core", "0280_source_code_resolve_run"),
    ]

    operations = []
