# Generated by Django 5.2.17 on 2026-10-07 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0281_merge_corrected_units_and_source_code_resolve"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientSourceCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_value", models.CharField(db_index=True, max_length=255)),
                (
                    "source_vocabulary_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("omop_table", models.CharField(blank=True, default="", max_length=30)),
                ("occurrence_count", models.IntegerField(default=1)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_codes",
                        to="omop_core.person",
                    ),
                ),
            ],
            options={
                "db_table": "patient_source_code",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "person",
                            "source_value",
                            "source_vocabulary_id",
                            "omop_table",
                        ),
                        name="uq_patient_source_code",
                    )
                ],
            },
        ),
    ]
