# Generated by Django 5.2.17 on 2026-10-07 17:49

import django.db.models.deletion
from django.db import migrations, models


# next_pk() draws ids from these sequences. note_nlp had none until imaging
# findings started writing it.
SEQUENCES = [('image_occurrence', 'image_occurrence_id'), ('note_nlp', 'note_nlp_id')]


def create_sequences(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    for table, pk in SEQUENCES:
        schema_editor.execute(f'CREATE SEQUENCE IF NOT EXISTS "{table}_{pk}_seq"')
        schema_editor.execute(
            f'SELECT setval(\'"{table}_{pk}_seq"\', COALESCE(MAX("{pk}"), 0) + 1, false) FROM "{table}"')


def drop_sequences(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    for table, pk in SEQUENCES:
        schema_editor.execute(f'DROP SEQUENCE IF EXISTS "{table}_{pk}_seq"')


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0281_merge_corrected_units_and_source_code_resolve'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOccurrence',
            fields=[
                ('image_occurrence_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('wadors_uri', models.CharField(blank=True, max_length=2048, null=True)),
                ('local_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('image_occurrence_date', models.DateField()),
                ('image_study_uid', models.CharField(blank=True, max_length=250, null=True)),
                ('image_series_uid', models.CharField(blank=True, max_length=250, null=True)),
                ('modality_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('anatomic_site_source_value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'image_occurrence',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='note_event_field_concept',
            field=models.ForeignKey(blank=True, db_column='note_event_field_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='note_event_fields', to='omop_core.concept'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_event_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='procedure_occurrence_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='procedure_occurrence_id of the imaging study this document reports', null=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['person', 'note_event_id'], name='ix_note_person_event'),
        ),
        migrations.AddField(
            model_name='imageoccurrence',
            name='anatomic_site_concept',
            field=models.ForeignKey(blank=True, db_column='anatomic_site_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_anatomic_sites', to='omop_core.concept'),
        ),
        migrations.AddField(
            model_name='imageoccurrence',
            name='modality_concept',
            field=models.ForeignKey(blank=True, db_column='modality_concept_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_modalities', to='omop_core.concept'),
        ),
        migrations.AddField(
            model_name='imageoccurrence',
            name='person',
            field=models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='omop_core.person'),
        ),
        migrations.AddField(
            model_name='imageoccurrence',
            name='procedure_occurrence',
            field=models.ForeignKey(db_column='procedure_occurrence_id', on_delete=django.db.models.deletion.CASCADE, related_name='image_occurrences', to='omop_core.procedureoccurrence'),
        ),
        migrations.AddField(
            model_name='imageoccurrence',
            name='visit_occurrence',
            field=models.ForeignKey(blank=True, db_column='visit_occurrence_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='omop_core.visitoccurrence'),
        ),
        migrations.AddIndex(
            model_name='imageoccurrence',
            index=models.Index(fields=['person', 'image_occurrence_date'], name='ix_image_person_date'),
        ),
        migrations.RunPython(create_sequences, drop_sequences),
    ]
