# Generated by Django 5.2.17 on 2026-10-08 16:33

import django.db.models.deletion
from django.db import migrations, models


def seed_hk_units_vocabulary(apps, schema_editor):
    Vocabulary = apps.get_model('omop_core', 'Vocabulary')
    Vocabulary.objects.get_or_create(
        vocabulary_id='HK-Units',
        defaults={
            'vocabulary_name': 'HealthKey local unit vocabulary',
            'vocabulary_reference': 'https://healthkey.ai',
            'vocabulary_version': '1.0',
            'vocabulary_concept_id': 0,
        },
    )


def reverse_seed(apps, schema_editor):
    Vocabulary = apps.get_model('omop_core', 'Vocabulary')
    Vocabulary.objects.filter(vocabulary_id='HK-Units').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0283_imaging_studies"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientsourcecode",
            name="example_quantity",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Representative quantity value(s) from source (e.g. "7.5", "120-140").',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="patientsourcecode",
            name="source_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Unparsed metadata from ETL (reference ranges, category, etc.).",
            ),
        ),
        migrations.AddField(
            model_name="patientsourcecode",
            name="source_unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Unit string as it arrived from the source (e.g. "mg/dL").',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="sourcecodeconceptmapping",
            name="destination_unit_concept",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="UCUM or HK-Units concept for the destination unit. Per-mapping, not per-destination-concept.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sccm_destination_units",
                to="omop_core.concept",
            ),
        ),
        migrations.RunPython(seed_hk_units_vocabulary, reverse_seed),
    ]
