"""Reviewed literal declarations in CancerBot migration source.

Hashes certify which definitions were inspected, not migration execution or
clinical correctness. In particular the legacy gene names and variant strings
are preserved without endorsing their biological interpretation.
"""

SEED_DECLARATIONS = {'0131_add_preexisting_categories.py': {'sha256': 'f0d0f1c2d7e2f3bcafdb47c683c87240349b6cb7c5e47ba6dcc598cb54769f99',
                                        'declarations': [('_add_preexisting_categories',
                                                          'data',
                                                          'PreExistingConditionCategory',
                                                          'preexisting_conditions',
                                                          {})]},
 '0150_populate_mutations.py': {'sha256': 'e4817a08864eeaab9a3d3d80e81bd91b7a296ccd2e0a7902c7c56e8644a3f1a0',
                                'declarations': [('_create_brca1_mutations',
                                                  'codes',
                                                  'BRCA1Mutation',
                                                  'genetic_mutations.variant_name',
                                                  {'gene': 'BRCA1'}),
                                                 ('_create_brca2_mutations',
                                                  'codes',
                                                  'BRCA2Mutation',
                                                  'genetic_mutations.variant_name',
                                                  {'gene': 'BRCA2'}),
                                                 ('_create_pik3ca_mutations',
                                                  'codes',
                                                  'PIK3CAMutation',
                                                  'genetic_mutations.variant_name',
                                                  {'gene': 'PIK3CA'}),
                                                 ('_create_tp53_mutations',
                                                  'codes',
                                                  'TP53Mutation',
                                                  'genetic_mutations.variant_name',
                                                  {'gene': 'TP53'}),
                                                 ('_create_esr1_mutations',
                                                  'codes',
                                                  'ESR1Mutation',
                                                  'genetic_mutations.variant_name',
                                                  {'gene': 'ESR1'})]},
 '0173_seed_ethnicity_and_scth.py': {'sha256': 'faa718cb94e207866a2c044f41031b0a5ec734e2780409f8b2e7679d33389bdb',
                                     'declarations': [('_seed_ethnicities', 'data', 'Ethnicity', 'ethnicity', {}),
                                                      ('_seed_scts',
                                                       'data',
                                                       'StemCellTransplant',
                                                       'stem_cell_transplant_history',
                                                       {})]},
 '0307_binetstage_patientinfo_binet_stage_and_more.py': {'sha256': '1ac1fc3bc0c390f1f76d081494cead3727812475c66c2ef25c11dbe44ff88341',
                                                         'declarations': [(None,
                                                                           'BINET_STAGE_DATA',
                                                                           'BinetStage',
                                                                           'binet_stage',
                                                                           {'disease': 'CLL'})]},
 '0308_proteinexpression_patientinfo_protein_expressions_and_more.py': {'sha256': 'd2f405337ee927949064518fa7fb47d8e91a1649b71b6759826f07080f9528b0',
                                                                        'declarations': [(None,
                                                                                          'PROTEIN_EXPRESSION_DATA',
                                                                                          'ProteinExpression',
                                                                                          'protein_expressions',
                                                                                          {'disease': 'CLL'})]},
 '0309_richtertransformation_patientinfo_richter_transformation_and_more.py': {'sha256': '70c83f6fe5ac3be69580fbd1659daf01d23cfaad2499d95592a0a66ae9e6eae6',
                                                                               'declarations': [(None,
                                                                                                 'RICHTER_TRANSFORMATION_DATA',
                                                                                                 'RichterTransformation',
                                                                                                 'richter_transformation',
                                                                                                 {'disease': 'CLL'})]},
 '0310_tumorburden_patientinfo_tumor_burden_and_more.py': {'sha256': 'dc92390b045be75db93671c9b49f19c9b45eff05bad2f4c3c1e2250a5de9c517',
                                                           'declarations': [(None,
                                                                             'TUMOR_BURDEN_DATA',
                                                                             'TumorBurden',
                                                                             'tumor_burden',
                                                                             {'disease': 'CLL'})]},
 '0352_mcl_foundation.py': {'sha256': '637bb9d3af8c979768766aa3203a11b55f28e11c9e5e3e228a0f55939d63d2fc',
                            'declarations': [(None,
                                              'MCL_PROTEIN_EXPRESSION_DATA',
                                              'ProteinExpression',
                                              'protein_expressions',
                                              {'disease': 'MCL'}),
                                             (None,
                                              'MORPHOLOGIC_VARIANT_DATA',
                                              'MorphologicVariant',
                                              'morphologic_variant',
                                              {'disease': 'MCL'})]},
 '0356_mcl_morphologic_variant_data.py': {'sha256': '309fbc028afed6648151de660addabe7cabade041c68312318d1cf1582d947bc',
                                          'declarations': [(None,
                                                            'MORPHOLOGIC_VARIANTS',
                                                            'MorphologicVariant',
                                                            'morphologic_variant',
                                                            {'disease': 'MCL'})]},
 '0364_mcl_extranodal_sites_data.py': {'sha256': 'f6a477c868e43cc094c61878d671d8b28a57501b2a8625c96530fae08352187e',
                                       'declarations': [(None,
                                                         'EXTRANODAL_SITES',
                                                         'ExtranodalSite',
                                                         'extranodal_sites',
                                                         {'disease': 'MCL'})]},
 '0366_mcl_bulky_disease_criteria_data.py': {'sha256': '715f8e52ba05a1ac9512757ab56861d076cc7f9c24f688ddfed3abb9bb0e962f',
                                             'declarations': [(None,
                                                               'BULKY_DISEASE_CRITERIA',
                                                               'BulkyDiseaseCriteria',
                                                               'bulky_disease_criteria',
                                                               {'disease': 'MCL'})]},
 '0370_mcl_high_risk_criteria_data.py': {'sha256': '8fa55edda5c47a28fa48db40928cd6b1da767e79814719e49c968905d6b20954',
                                         'declarations': [(None,
                                                           'HIGH_RISK_MCL_CRITERIA',
                                                           'HighRiskMclCriteria',
                                                           'high_risk_mcl_criteria',
                                                           {'disease': 'MCL'})]},
 '0381_mcl_high_risk_criteria_granularity.py': {'sha256': 'c27e27b53b79aa63bb1e051937b0a126c08b1c199c56ef0073df4073d4fe99b9',
                                                'declarations': [(None,
                                                                  'NEW_HIGH_RISK_MCL_CRITERIA',
                                                                  'HighRiskMclCriteria',
                                                                  'high_risk_mcl_criteria',
                                                                  {'disease': 'MCL'})]},
 '0393_mcl_high_mipi_simplified.py': {'sha256': '78fffc6b85357f0407bbace21aebefda04d9556791b1e911aad81da6a2fc178d',
                                      'declarations': [(None,
                                                        'NEW_HIGH_RISK_MCL_CRITERIA',
                                                        'HighRiskMclCriteria',
                                                        'high_risk_mcl_criteria',
                                                        {'disease': 'MCL'})]},
 '0395_seed_palb1_mutations.py': {'sha256': '8946f92a3cff28555376046a8d86a20b679e480b15e7dbd1c013185ba6bf165c',
                                  'declarations': [(None,
                                                    'PALB1_VARIANTS',
                                                    'MutationCode',
                                                    'genetic_mutations.variant_name',
                                                    {'gene': 'PALB1', 'source_code_transform': 'palb1_variant'}),
                                                   (None,
                                                    'PALB1_ORIGINS',
                                                    'MutationOrigin',
                                                    'genetic_mutations.origin',
                                                    {'gene': 'PALB1'})]}}
