"""
Django settings for ctomop project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file (for local development)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-your-default-key-change-this')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

if not DEBUG:
    import sys as _sys
    # Skip the production guard for management commands that must run before the
    # app server is fully initialised (migrate, test, collectstatic, check, etc.)
    # so that Render deploys (which call `migrate` in start.sh) and CI test runs
    # are not broken when DATABASE_URL is absent at import time.
    _management_commands = {'migrate', 'test', 'collectstatic', 'check', 'makemigrations', 'shell'}
    _running_mgmt = bool(set(_sys.argv) & _management_commands)
    if not _running_mgmt:
        from django.core.exceptions import ImproperlyConfigured
        _config_errors = []
        if SECRET_KEY.startswith('django-insecure-'):
            _config_errors.append(
                'SECRET_KEY must be set to a strong random value (current value is the insecure default)'
            )
        if not os.environ.get('DATABASE_URL'):
            _config_errors.append(
                'DATABASE_URL must be set (SQLite is not supported in production)'
            )
        if _config_errors:
            raise ImproperlyConfigured(
                'Missing required production settings:\n'
                + '\n'.join(f'  - {e}' for e in _config_errors)
            )

if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [
        h.strip()
        for h in os.environ.get('ALLOWED_HOSTS', 'ctomop.onrender.com').split(',')
        if h.strip()
    ]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'oauth2_provider',
    'omop_core',
    'omop_genomics',
    'omop_oncology',
    'patient_portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'patient_portal.api.middleware.AuditLogMiddleware',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'audit_json': {
            '()': 'logging.Formatter',
            'format': '%(message)s',
        },
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'audit_stdout': {
            'class': 'logging.StreamHandler',
            'formatter': 'audit_json',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'audit': {
            'handlers': ['audit_stdout'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'patient_portal': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

ROOT_URLCONF = 'ctomop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'build'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ctomop.wsgi.application'

# Database
_db_url = os.environ.get('DATABASE_URL')
if _db_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=_db_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

AUTH_USER_MODEL = "patient_portal.Identity"

AUTHENTICATION_BACKENDS = [
    "patient_portal.backends.EmailBackend",
]

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = []

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

_whitenoise_root = os.environ.get('WHITENOISE_ROOT', '')
if _whitenoise_root:
    WHITENOISE_ROOT = Path(_whitenoise_root)
else:
    for _candidate in (BASE_DIR / 'frontend' / 'dist' / 'remote', BASE_DIR / 'frontend' / 'build'):
        if _candidate.exists():
            WHITENOISE_ROOT = _candidate
            break

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        origin.strip()
        for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
        if origin.strip()
    ]
CORS_ALLOW_CREDENTIALS = True

# ── Pluggable partner auth providers ──────────────────────────────────────
# PartnerAuthentication iterates these in order; the first provider that
# recognises the bearer token wins.
PARTNER_AUTH_PROVIDERS = [
    "patient_portal.api.providers.firebase.FirebaseTokenProvider",
]

FIREBASE_PROJECT_ID = os.environ.get("FIREBASE_PROJECT_ID", "healthtree-test" if DEBUG else "")
FIREBASE_SKIP_REVOCATION_CHECK = os.environ.get(
    "FIREBASE_SKIP_REVOCATION_CHECK", "true" if DEBUG else "false"
).lower() in ("1", "true")

AUTH_TOKEN_CACHE_TTL = int(os.environ.get("AUTH_TOKEN_CACHE_TTL", "60"))

# REST Framework
SERVICE_AUTH_TOKEN = os.environ.get("SERVICE_AUTH_TOKEN", "")

_auth_classes = [
    'patient_portal.api.authentication.ServiceTokenAuthentication',
    'patient_portal.api.authentication.PartnerAuthentication',
    'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
]
if DEBUG:
    _auth_classes += [
        'rest_framework.authentication.BasicAuthentication',
        'patient_portal.api.authentication.CsrfExemptSessionAuthentication',
    ]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': _auth_classes,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',
        'user': '300/minute',
        'sync': '10/minute',
    },
}

# SMART on FHIR / OAuth2 provider configuration
OAUTH2_PROVIDER = {
    'SCOPES': {
        'openid':           'OpenID Connect identity token',
        'fhir-user':        'FHIR User profile',
        'launch':           'SMART launch context',
        'launch/patient':   'Patient-level launch context',
        'offline_access':   'Offline access (refresh tokens)',
        'patient/*.read':   'Read all patient clinical data',
        'patient/*.write':  'Write all patient clinical data',
        'user/*.read':      'Read data on behalf of the current user',
        'user/*.write':     'Write data on behalf of the current user',
    },
    'DEFAULT_SCOPES': ['openid', 'patient/*.read'],
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 86400 * 30,
    # Require PKCE for all public (SPA) clients
    'PKCE_REQUIRED': True,
    # Allow http for local dev; https enforced in production via ALLOWED_REDIRECT_URI_SCHEMES
    'ALLOWED_REDIRECT_URI_SCHEMES': ['https', 'http'],
    # client_credentials enables service-to-service auth for any API client
    # (hospital systems, foundations, platform services) without a user session
    'ALLOWED_GRANT_TYPES': [
        'authorization_code',
        'client_credentials',
        'refresh_token',
    ],
    'OIDC_ENABLED': True,
    'OIDC_ISS_ENDPOINT': os.environ.get('OIDC_ISS_ENDPOINT', ''),
}
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')

# Security settings for production
if not DEBUG:
    # Don't force SSL redirect - Render handles SSL at load balancer
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Add trusted origins for CSRF
    production_url = os.environ.get('PRODUCTION_URL', '')
    railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
    render_url = os.environ.get('RENDER_EXTERNAL_URL', '')
    
    csrf_origins = []
    if production_url:
        csrf_origins.append(production_url)
    if railway_domain:
        csrf_origins.append(f'https://{railway_domain}')
    if render_url:
        csrf_origins.append(render_url)
    
    CSRF_TRUSTED_ORIGINS = csrf_origins


# ── Firebase Admin SDK ────────────────────────────────────────────────────
def _init_firebase_admin():
    try:
        import firebase_admin
        from firebase_admin import credentials as fb_credentials
    except ImportError:
        return

    if firebase_admin._apps:
        return

    project_id = FIREBASE_PROJECT_ID
    options = {"projectId": project_id} if project_id else {}

    if os.environ.get("FIREBASE_AUTH_EMULATOR_HOST"):
        class _EmulatorCredential(fb_credentials.Base):
            def get_credential(self):
                return None
        cred = _EmulatorCredential()
    else:
        try:
            cred = fb_credentials.ApplicationDefault()
        except Exception:
            return

    try:
        firebase_admin.initialize_app(cred, options)
    except ValueError:
        pass  # Already initialized
    except Exception:
        import logging
        logging.getLogger(__name__).warning(
            "Firebase Admin SDK initialization failed", exc_info=True,
        )


_init_firebase_admin()
