"""
Django settings for ctomop project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file (for local development)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-your-default-key-change-this')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'oauth2_provider',
    'omop_core',
    'omop_genomics',
    'omop_oncology',
    'patient_portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'patient_portal.api.middleware.AuditLogMiddleware',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'audit_json': {
            '()': 'logging.Formatter',
            'format': '%(message)s',
        },
    },
    'handlers': {
        'audit_stdout': {
            'class': 'logging.StreamHandler',
            'formatter': 'audit_json',
        },
    },
    'loggers': {
        'audit': {
            'handlers': ['audit_stdout'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

ROOT_URLCONF = 'ctomop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'build'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ctomop.wsgi.application'

# Database
_db_url = os.environ.get('DATABASE_URL')
if _db_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=_db_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Only include frontend static files if they exist
frontend_static = BASE_DIR / 'frontend' / 'build' / 'static'
if frontend_static.exists():
    STATICFILES_DIRS = [frontend_static]
else:
    STATICFILES_DIRS = []

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings - Allow all for now
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# ── Pluggable partner auth providers ──────────────────────────────────────
# PartnerAuthentication iterates these in order; the first provider that
# recognises the bearer token wins.
PARTNER_AUTH_PROVIDERS = [
    "patient_portal.api.providers.firebase.FirebaseTokenProvider",
]

FIREBASE_PROJECT_ID = os.environ.get("FIREBASE_PROJECT_ID", "healthtree-test")
FIREBASE_SKIP_REVOCATION_CHECK = os.environ.get("FIREBASE_SKIP_REVOCATION_CHECK", "true").lower() in ("1", "true")

# REST Framework
SERVICE_AUTH_TOKEN = os.environ.get("SERVICE_AUTH_TOKEN", "")

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'patient_portal.api.authentication.ServiceTokenAuthentication',
        'patient_portal.api.authentication.PartnerAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.BasicAuthentication',
        'patient_portal.api.authentication.CsrfExemptSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# SMART on FHIR / OAuth2 provider configuration
OAUTH2_PROVIDER = {
    'SCOPES': {
        'openid':           'OpenID Connect identity token',
        'fhir-user':        'FHIR User profile',
        'launch':           'SMART launch context',
        'launch/patient':   'Patient-level launch context',
        'offline_access':   'Offline access (refresh tokens)',
        'patient/*.read':   'Read all patient clinical data',
        'patient/*.write':  'Write all patient clinical data',
        'user/*.read':      'Read data on behalf of the current user',
        'user/*.write':     'Write data on behalf of the current user',
    },
    'DEFAULT_SCOPES': ['openid', 'patient/*.read'],
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 86400 * 30,
    # Require PKCE for all public (SPA) clients
    'PKCE_REQUIRED': True,
    # Allow http for local dev; https enforced in production via ALLOWED_REDIRECT_URI_SCHEMES
    'ALLOWED_REDIRECT_URI_SCHEMES': ['https', 'http'],
    # client_credentials enables service-to-service auth for any API client
    # (hospital systems, foundations, platform services) without a user session
    'ALLOWED_GRANT_TYPES': [
        'authorization_code',
        'client_credentials',
        'refresh_token',
    ],
    'OIDC_ENABLED': True,
    'OIDC_ISS_ENDPOINT': os.environ.get('OIDC_ISS_ENDPOINT', ''),
}
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')

# Security settings for production
if not DEBUG:
    # Don't force SSL redirect - Render handles SSL at load balancer
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Add trusted origins for CSRF
    production_url = os.environ.get('PRODUCTION_URL', '')
    railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
    render_url = os.environ.get('RENDER_EXTERNAL_URL', '')
    
    csrf_origins = []
    if production_url:
        csrf_origins.append(production_url)
    if railway_domain:
        csrf_origins.append(f'https://{railway_domain}')
    if render_url:
        csrf_origins.append(render_url)
    
    CSRF_TRUSTED_ORIGINS = csrf_origins


# ── Firebase Admin SDK ────────────────────────────────────────────────────
def _init_firebase_admin():
    import firebase_admin
    from firebase_admin import credentials as fb_credentials

    if firebase_admin._apps:
        return

    project_id = FIREBASE_PROJECT_ID
    options = {"projectId": project_id} if project_id else {}

    if os.environ.get("FIREBASE_AUTH_EMULATOR_HOST"):
        class _EmulatorCredential(fb_credentials.Base):
            def get_credential(self):
                return None
        cred = _EmulatorCredential()
    else:
        cred = fb_credentials.ApplicationDefault()

    try:
        firebase_admin.initialize_app(cred, options)
    except ValueError:
        pass


_init_firebase_admin()
