# Generated by Django 4.2.16 on 2026-05-22 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0070_add_loinc_code_class'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('patient_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_user', to='omop_core.person')),
            ],
            options={
                'db_table': 'patient_user',
            },
        ),
        migrations.CreateModel(
            name='PatientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sender_is_patient', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='patient_portal.patientuser')),
            ],
            options={
                'db_table': 'patient_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('data_sharing', 'Data Sharing'), ('clinical_trial', 'Clinical Trial Participation'), ('research', 'Research Use')], max_length=50)),
                ('consent_granted', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
                ('consent_document', models.TextField(blank=True, null=True)),
                ('patient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patient_portal.patientuser')),
            ],
            options={
                'db_table': 'patient_consent',
                'unique_together': {('patient_user', 'consent_type')},
            },
        ),
    ]
