# Generated by Django 4.2.16 on 2026-07-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0004_rename_patient_user_user_id_to_identity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Grants premium-tier feature access (e.g. data export) across all connected apps.'),
        ),
    ]
