# Generated by Django 4.2.16 on 2026-07-24 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0118_seed_hk_vocabularies_remap_fhir_concepts'),
        ('patient_portal', '0005_add_identity_is_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_invitations', to='omop_core.person')),
            ],
            options={
                'db_table': 'patient_invitation',
            },
        ),
        migrations.AddConstraint(
            model_name='patientinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('cancelled_at__isnull', True)), fields=('person',), name='uq_patient_invitation_pending'),
        ),
    ]
