# Generated by Django 5.2.6 on 2026-07-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_portal", "0006_patientinvitation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientconsent",
            name="consent_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
