# Generated by Django 5.2.6 on 2026-07-25 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_portal", "0007_consent_date_auto_now"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientmessage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent message for threading (null = top-level message)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="patient_portal.patientmessage",
            ),
        ),
        migrations.AddField(
            model_name="patientmessage",
            name="read_at",
            field=models.DateTimeField(
                blank=True, help_text="When the message was read", null=True
            ),
        ),
        migrations.AddField(
            model_name="patientmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                help_text="Identity of the sender",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
