# Generated by Django 4.2.16 on 2026-07-26 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0008_patientmessage_parent_patientmessage_read_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('record_view', 'Record view'), ('record_create', 'Record create'), ('record_update', 'Record update'), ('record_delete', 'Record delete'), ('auth', 'Authentication'), ('consent', 'Consent'), ('other', 'Other')], db_index=True, max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=512)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_email', models.CharField(blank=True, max_length=254, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', '-timestamp'], name='audit_user_ts_idx'), models.Index(fields=['event_type', '-timestamp'], name='audit_type_ts_idx')],
            },
        ),
    ]
