# Generated by Django 5.2.6 on 2026-07-26 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0009_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='failed_login_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='identity',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='If set and in the future, local logins are refused (lockout).', null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force a password change on next successful login (e.g. after an admin reset).'),
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identity', '-created_at'], name='pwhist_identity_ts_idx')],
            },
        ),
    ]
