# Generated by Django 5.2.6 on 2026-07-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0010_identity_failed_login_count_identity_locked_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('record_view', 'Record view'), ('record_create', 'Record create'), ('record_update', 'Record update'), ('record_delete', 'Record delete'), ('auth', 'Authentication'), ('consent', 'Consent'), ('admin', 'Administrative / system'), ('audit_review', 'Audit-log access'), ('other', 'Other')], db_index=True, max_length=32),
        ),
    ]
