# Generated by Django 5.2.6 on 2026-07-26 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0011_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('record_view', 'Record view'), ('record_create', 'Record create'), ('record_update', 'Record update'), ('record_delete', 'Record delete'), ('auth', 'Authentication'), ('consent', 'Consent'), ('admin', 'Administrative / system'), ('audit_review', 'Audit-log access'), ('break_glass', 'Break-glass emergency access'), ('other', 'Other')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='BreakGlassGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.BigIntegerField(db_index=True)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_glass_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'break_glass_grant',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identity', 'expires_at'], name='breakglass_identity_exp_idx')],
            },
        ),
    ]
