# Generated by Django 5.2.6 on 2026-07-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0012_auditevent_signature_alter_auditevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmessage',
            name='confidentiality',
            field=models.CharField(choices=[('normal', 'Normal'), ('restricted', 'Restricted'), ('very_restricted', 'Very restricted')], db_index=True, default='normal', help_text='Sensitivity level (PHR-S FM PH.6.3#08); restricted messages are hidden from staff other than the sender.', max_length=20),
        ),
    ]
