# Generated by Django 5.2.6 on 2026-07-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0013_patientmessage_confidentiality'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='chain_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
