# Generated by Django 5.2.17 on 2026-09-12 15:06

import django.db.models.deletion
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_portal", "0015_fix_patient_user_identity_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("service_id", models.CharField(max_length=128, unique=True, validators=[
                    django.core.validators.RegexValidator(
                        r'^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$',
                        'Use letters, numbers, dots, underscores, or hyphens.',
                    ),
                ])),
                ("description", models.TextField(blank=True)),
                ("owner_contact", models.CharField(blank=True, max_length=255)),
                (
                    "scopes",
                    models.CharField(
                        blank=True, default="patient/*.read", max_length=512
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ServiceAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=160)),
                (
                    "digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("suffix", models.CharField(editable=False, max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_service_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_service_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tokens",
                        to="patient_portal.serviceapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
