# Generated by Django 5.2.17 on 2026-09-16 08:12

import patient_portal.service_tokens
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0017_seed_service_application_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapplication',
            name='scopes',
            field=models.CharField(blank=True, default='patient/*.read', max_length=512, validators=[patient_portal.service_tokens.validate_service_scopes]),
        ),
    ]
