# Generated by Django 5.2.17 on 2026-09-12 15:24

import django.db.models.deletion
import django.utils.timezone
import patient_portal.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omop_core", "0230_cytogenetic_marker_choices"),
        ("patient_portal", "0017_seed_service_application_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048, validators=[patient_portal.models.validate_webhook_subscription_url])),
                ("event_types", models.JSONField()),
                (
                    "secret",
                    models.CharField(
                        default=patient_portal.models.webhook_secret,
                        editable=False,
                        max_length=128,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omop_core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("retry", "Retry"),
                            ("delivered", "Delivered"),
                            ("dead_letter", "Dead letter"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("response_status", models.PositiveSmallIntegerField(null=True)),
                ("error", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="patient_portal.webhooksubscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InboundWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("event_id", models.CharField(max_length=128)),
                ("event_type", models.CharField(max_length=64)),
                ("payload_digest", models.CharField(max_length=64)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="omop_core.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "event_id"),
                        name="unique_inbound_webhook_event",
                    )
                ],
            },
        ),
    ]
