# Generated by Django 5.2.17 on 2026-10-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0020_identity_email_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loinc_code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(blank=True, default='', help_text='Display name; blank uses the LOINC concept name.', max_length=120)),
                ('rank', models.PositiveIntegerField(help_text='Lower is more important. Unranked tests sort after ranked ones.')),
                ('panels', models.JSONField(blank=True, default=list, help_text='Panels this test belongs to, e.g. ["CBC"] or ["BMP", "CMP"].')),
                ('disease_slugs', models.JSONField(blank=True, default=list, help_text='Cancers this test is a disease marker for (PatientRecord.disease_slug values).')),
            ],
            options={
                'ordering': ['rank', 'loinc_code'],
            },
        ),
    ]
