# Generated by Django 5.2.17 on 2026-09-14 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_portal", "0021_webhooksubscription_webhookdelivery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookdelivery",
            name="next_attempt_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                condition=models.Q(("status__in", ["pending", "retry", "sending"])),
                fields=["next_attempt_at"],
                name="webhook_due_active_idx",
            ),
        ),
    ]
