# Generated by Django 5.2.17 on 2026-10-06 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0279_field_mapping_provenance_text'),
        ('patient_portal', '0022_seed_lab_markers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('medication', 'Medication'), ('medication_note', 'Note on a medication'), ('therapy_line', 'Line of therapy'), ('condition', 'Condition the patient added'), ('procedure', 'Procedure the patient added')], max_length=20)),
                ('subject_key', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('taking', "I'm taking it"), ('not_taking', 'Not taking'), ('took', 'I took it'), ('not_taken', 'Not taken'), ('stopped', 'I stopped taking this'), ('end_reason', 'Why the line ended'), ('note', 'Note'), ('entry', 'Added by the patient')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=40)),
                ('note', models.TextField(blank=True, default='')),
                ('stopped_on', models.DateField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_statements', to='omop_core.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'subject', 'subject_key'), name='uq_patient_statement_item')],
            },
        ),
    ]
