# Generated by Django 5.2.17 on 2026-09-23 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0255_merge_0254_patientrecord_ix_pr_email_upper_and_schema_drift_cleanup'),
        ('patient_portal', '0022_webhook_active_delivery_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdelivery',
            name='destination_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='webhooksubscription',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WebhookSubscriptionChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_pk', models.PositiveIntegerField()),
                ('organization_slug', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=16)),
                ('url_before', models.URLField(blank=True, max_length=2048)),
                ('url_after', models.URLField(blank=True, max_length=2048)),
                ('event_types_before', models.JSONField(null=True)),
                ('event_types_after', models.JSONField(null=True)),
                ('active_before', models.BooleanField(null=True)),
                ('active_after', models.BooleanField(null=True)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='omop_core.organization')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='patient_portal.webhooksubscription')),
            ],
            options={
                'db_table': 'webhook_subscription_change',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription_pk', '-created_at'], name='webhook_change_sub_ts_idx'), models.Index(fields=['organization_slug', '-created_at'], name='webhook_change_org_ts_idx')],
            },
        ),
    ]
