# Generated by Django 5.2.17 on 2026-09-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_portal", "0023_webhookdelivery_destination_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhooksubscriptionchange",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Created"),
                    ("update", "Updated"),
                    ("delete", "Deleted"),
                    ("rotate_secret", "Signing secret rotated"),
                ],
                max_length=16,
            ),
        ),
    ]
