# Generated by Django 5.2.17 on 2026-10-06 22:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0279_field_mapping_provenance_text'),
        ('patient_portal', '0023_patient_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=16, unique=True)),
                ('recipient', models.CharField(choices=[('checkin', 'Appointment check-in (care center)'), ('doctor', 'Doctor'), ('family', 'Caregiver or family member'), ('other', 'Other')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('method', models.CharField(choices=[('email', 'Email invite'), ('link', 'Private link'), ('qr', 'QR code')], max_length=5)),
                ('selection', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_shares', to='omop_core.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='patient_portal.recordshare')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recordshare',
            index=models.Index(fields=['person', '-created_at'], name='record_share_person_idx'),
        ),
    ]
