# Generated by Django 5.2.17 on 2026-09-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_portal", "0024_alter_webhooksubscriptionchange_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookdelivery",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
