# Generated by Django 5.2.17 on 2026-10-07 01:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omop_core', '0279_field_mapping_provenance_text'),
        ('patient_portal', '0024_record_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('diagnosis', 'About your diagnosis'), ('lab_test', 'What the test measures'), ('lab_result', 'What your results mean'), ('genetic_test', 'What a genetic result means'), ('imaging_study', 'What a scan showed')], max_length=20)),
                ('target_key', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('prompt_version', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=100)),
                ('source_hash', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_explanations', to='omop_core.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'kind', 'target_key'), name='uq_ai_explanation_item')],
            },
        ),
    ]
